:: Copyright (c) 2019 Andre Attamimi
:: License: http://opensource.org/licenses/MIT

@echo off

call :testCommands "doskey.exe"
if errorlevel 1 (
    echo %~n0: Error - cannot find 'doskey.exe'.
    exit /b 1
)

if "%ALIASES%"=="" set "ALIASES=%USERPROFILE%\aliases.txt"

if /i "%ALIASES%"=="%USERPROFILE%\aliases.txt" (
    if not exist "%ALIASES%" call :sample >"%ALIASES%"
    doskey.exe alias="%~f0" $*
    doskey.exe /macrofile="%ALIASES%" >nul
)

if "%~1"=="" (
    echo Try '%~nx0 /?' for more information.
    echo.& doskey.exe /macros
    exit /b 0
) else if "%~1"=="/?" (
    goto :usage
) else if "%~1"=="/h" (
    goto :usage
) else if "%~1"=="/f" (
    if "%~2"=="" (
        echo %~n0: Requires file path.
        exit /b 1
    ) else if exist "%~f2\" (
        echo %~n0: Is not a file '%~2'.
    ) else if not exist "%~f2" (
        echo %~n0: File not found '%~f2'.
    ) else (
        set "ALIASES=%~f2"
        doskey.exe /macrofile="%~f2" >nul
        exit /b 0
    )
    exit /b 2
) else if "%~1"=="/d" (
    if "%~2"=="" (
        echo %~n0: Requires alias name.
        exit /b 1
    )
    setlocal
    set "ALIAS_NAME=%~2"
    set "ALIAS_VALUE="
    doskey.exe %~2 =
    goto :filter
) else if "%~1"=="/reload" (
    set /p x="Reloading aliases ..." <nul
    doskey.exe /macrofile="%ALIASES%" >nul
    timeout /t 1 /nobreak >nul
    echo. done!
    exit /b 0
) else if "%~2"=="" (
    doskey.exe /macros | findstr.exe /ib "%~1" 2>nul
    exit /b 0
)

setlocal
set "ALIAS_NAME="
set "ALIAS_VALUE="
for /f "tokens=1,* delims==," %%A in ("%*") do (
    set "ALIAS_NAME=%%A" & set "ALIAS_VALUE=%%B"
)
if not ["%ALIAS_NAME: =%"] == ["%ALIAS_NAME%"] (
    echo %~n0: The alias name cannot contains spaces.
    exit /b 1
)
goto :filter

:filter
findstr.exe /v /b /c:"%ALIAS_NAME%=" "%ALIASES%">"%temp%\aliases.tmp"
if defined ALIAS_VALUE echo:%ALIAS_NAME%=%ALIAS_VALUE%>>"%temp%\aliases.tmp"
type "%temp%\aliases.tmp">"%ALIASES%" && del /f /q "%temp%\aliases.tmp"
doskey.exe /macrofile="%ALIASES%" >nul
exit /b 0

:sample
@echo:== Starting with equals ^(=^) will not be executed.
@echo:== Uncoment and/or add your aliases below:
@echo:= cp=copy $*
@echo:= ll=dir /o $*$Bfindstr /b [0-9]
@echo:= ls=dir $*
@echo:= mv=move $*
@echo:= rm=del $*
@echo:= ni=if not "$1"=="" echo/$G$1:1
@echo:.=if not exist "$1" ^(exit /b 2^) else call $*
@echo:~=pushd "%%USERPROFILE%%"
@echo:np=notepad $1
@echo:e.=explorer .
@goto:EOF

:usage
echo.Define, display, or import aliases on cmd.exe.
echo.  %~nx0 - a aliases of the doskey.exe
echo.
echo.Usage: %~nx0 [/d] [name[=value] ... ]
echo.   or: %~nx0 [/f filename.] ^| [/reload]
echo.   or: %~nx0 [/?, /h [all]]
echo.
echo.  Without arguments display aliases. The env-var
echo.  aliases file is %%ALIASES%%. Recommended to define
echo.  or remove entries in ALIASES file.
if not "%~2"=="all" (
    echo.
    echo.Type '%~nx0 /? all' for more all information.
    exit /b 0
)
echo.
echo.The following special codes on values:
echo.  $1-$9      Equivalent to parameters ^(%%1-%%9^).
echo.  $*         Represents all command-lines ^(%%*^).
echo.  $B         Equivalent to using pipelines ^(^|^).
echo.  $T         Allows multiple commands ^(^&^).
echo.  $L         Equivalent to redirect inputs ^(^<^)
echo.  $G         Equivalent to redirect outputs ^(^>^).
echo.
echo.In the %~nx0 command, utilize these notations:
echo.  ^^%%         Escaped to env-var in this script ^(%%^).
echo.
echo.Examples:
echo   C:\^>:: Escaped to enviroment variable sign:
echo.  C:\^>%~nx0 edit="%%windir%%\notepad.exe" "^%%ALIASES^%%"
echo.  edit="C:\Windows\notepad.exe" "%%ALIASES%%"
echo.
echo   C:\^>:: Appends output to the end of a file:
echo   C:\^>%~nx0 save=doskey /macros $G$G "^%%ALIASES^%%"
echo   save=doskey /macros ^>^> "%%ALIASES%%"
exit /b 0

:checkCommand
if "%~$PATH:1"=="" exit /b 1
exit /b 0

:testCommands
call :checkCommand "%~nx1"
if %errorlevel% equ 0 exit /b 0

call :checkCommand certutil.exe
if %errorlevel% neq 0 exit /b 1

setlocal enabledelayedexpansion
set "encodelabel=encode%~n1Exe"
set "outputDir=%APPDATA%\alias.d"
set "outputFile=%outputDir%\%~n1.exe"
set "inputFile=%outputFile%.b64"

if not exist "%outputDir%\" mkdir "%outputDir%\"
call :%encodelabel% > "%inputFile%"
certutil.exe -f -decode "%inputFile%" "%outputFile%" >nul

if %errorlevel% neq 0 (
    endlocal
    exit /b 1
)

set "DUMP=%outputDir%;!PATH:%outputDir%;=!"
endlocal & set "PATH=%DUMP%"
exit /b 0

:encodeDoskeyExe -- Derived from the original source.
 @echo:off
 @echo:-----BEGIN CERTIFICATE-----
 @echo:TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAA4AAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5v
 @echo:dCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAAAHWOI8QzmMb0M5jG9DOYxv
 @echo:V1KJbkI5jG9XUo9uQTmMb1dSiG5SOYxvV1KNbko5jG9DOY1vIzmMb1dShG5BOYxv
 @echo:V1Jzb0I5jG9XUo5uQjmMb1JpY2hDOYxvAAAAAAAAAABQRQAAZIYGAPSliIgAAAAA
 @echo:AAAAAPAAIgALAg4UACYAAAAsAAAAAAAAAC8AAAAQAAAAAABAAQAAAAAQAAAAAgAA
 @echo:CgAAAAoAAAAKAAAAAAAAAACgAAAABAAAN/MAAAMAYMEAAAgAAAAAAAAgAAAAAAAA
 @echo:AAAQAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAACUSQAAZAAAAACAAAAACAAA
 @echo:AHAAABQBAAAAAAAAAAAAAACQAAAgAAAAoEUAAFQAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAQQAAAGAEAAAAAAAAAAAAAKEEAAPACAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAudGV4dAAAALAkAAAAEAAAACYAAAAEAAAAAAAAAAAAAAAAAAAgAABg
 @echo:LnJkYXRhAAB+FwAAAEAAAAAYAAAAKgAAAAAAAAAAAAAAAAAAQAAAQC5kYXRhAAAA
 @echo:eAYAAABgAAAAAgAAAEIAAAAAAAAAAAAAAAAAAEAAAMAucGRhdGEAABQBAAAAcAAA
 @echo:AAIAAABEAAAAAAAAAAAAAAAAAABAAABALnJzcmMAAAAACAAAAIAAAAAIAAAARgAA
 @echo:AAAAAAAAAAAAAAAAQAAAQC5yZWxvYwAAIAAAAACQAAAAAgAAAE4AAAAAAAAAAAAA
 @echo:AAAAAEAAAEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAMzMzMzMzMzMQFNIg+wgi0EYSIvZg/gCckxIi0kQZoM5
 @echo:InVCjVD/O9BzBg+3DFHrBbn//wAAZoP5InUqQbgBAAAASIvLSP8V3TIAAA8fRAAA
 @echo:M9JIi8tEjUIBSP8VyDIAAA8fRAAASIPEIFvDzMzMzMzMzMzMSIvESIlYCEiJaBBI
 @echo:iXAYV0FWQVdIgeyQAAAATIvxTYv5SI1IiEGK6IvySP8VYzMAAA8fRAAASI1MJGBI
 @echo:/xVSMwAADx9EAAAz24v7hfYPhLoAAACF/3QOjUf/ZkE5HEYPhZ4AAABBg8j/SI1M
 @echo:JDBIjRWrMwAAQITtdQdIjRWbMwAASP8VzDEAAA8fRAAAhMB0fovHSI1MJGBBg8j/
 @echo:SY0URkj/FeUxAAAPH0QAAITAdF9IjVQkYEiNTCQwSP8VAzIAAA8fRAAAhMB0RUmL
 @echo:B0G5AwAAAEUzwLoeBAAASYvPSItAIP8VxDIAAEyNRCQwSYvPSI0VMTMAAEj/FdYx
 @echo:AAAPH0QAAP/HO/4Pgkb///+zAUiNTCRgSP8VCTEAAA8fRAAASI1MJDBI/xX4MAAA
 @echo:Dx9EAABMjZwkkAAAAIrDSYtbIEmLayhJi3MwSYvjQV9BXl/DzMzMzMzMzMxIiVwk
 @echo:CEiJbCQQSIl0JBhXQVZBV0iD7DBEi0kYM+1IiSpJi/BJiShMi/JIi/kPt8WL3UG/
 @echo://8AAGZBuyAARYXJdCFBO9lzDEiLRxCLyw+3BEjrA0GLx2ZBO8N1B//DQTvZcuRE
 @echo:i9PrGEiLRxCLyw+3BEhmQTvDdA1mg/g9dAf/w0E72XLjRIvDRDvTD4TcAAAA6xJI
 @echo:i0cQi8sPtwRIZkE7w3UH/8NBO9ly6WaD+D0PhbkAAADrDkiLRxAPtxRYZkE703UH
 @echo:/8NBO9ly60UrwsZEJCgBRTPJiWwkIEGL0kiLz0j/FX0wAAAPH0QAAEUzycZEJCgB
 @echo:QYPI/0mJBovTiWwkIEiLz0j/FVkwAAAPH0QAAE2LBkiJBk2FwHQpSIXAdASwAetL
 @echo:TYXAdBtlSIsMJWAAAAAz0kiLSTBI/xVtLwAADx9EAABMiwZJiS5NhcB0G2VIiwwl
 @echo:YAAAADPSSItJMEj/FUcvAAAPH0QAAEiJLjLASItcJFBIi2wkWEiLdCRgSIPEMEFf
 @echo:QV5fw8zMzMzMzMzMSIvESIlYCEiJaBBIiXAYSIl4IEFWSIPsQEmL8ESK8kiL6Uj/
 @echo:FSMuAAAPH0QAAGVIiwwlYAAAADPSi9hEjUABSItJMEj/FdouAAAPH0QAAEiL+EiF
 @echo:wHVOSI0N5jAAAEj/FZcvAAAPH0QAAMdEJDADAQAASIlEJChBuQMAAABIjQXgMAAA
 @echo:ujwEAABIi85IiUQkIEWNQf5I/xVYLwAADx9EAAAywOtthdt0FkyLxYvTSIvPSP8V
 @echo:1C0AAA8fRAAAi9jR60yLzovTRYrGSIvP6Ef8//+EwHUdSI0NaDAAAEj/FRkvAAAP
 @echo:H0QAAMdEJDANAQAA64BlSIsMJWAAAABMi8cz0kiLSTBI/xURLgAADx9EAACwAUiL
 @echo:XCRQSItsJFhIi3QkYEiLfCRoSIPEQEFew8zMzMzMzMxIi8RIiVgISIlwEEiJeBhM
 @echo:iWggVUFWQVdIjWihSIHsoAAAAEyL8UiNTRdI/xVHLwAADx9EAABIjU3nSP8VNy8A
 @echo:AA8fRAAASP8VEy0AAA8fRAAAZUiLDCVgAAAAM9KL+ESNQAFIi0kwSP8Vgi0AAA8f
 @echo:RAAAM9tMi/hIhcB1IEiNDYwvAABI/xU9LgAADx9EAADHRCQwNQEAAOm+AQAAhf90
 @echo:E4vXSYvPSP8ViywAAA8fRAAAi/jR74vzD4Q8AQAAhfZ0Do1G/2ZBORxHD4UgAQAA
 @echo:i8ZIjU0XQYPI/02NLEdJi9VI/xWILQAADx9EAACEwA+ESwEAAEGDyP9IjRU4LwAA
 @echo:SI1N50j/FS0tAAAPH0QAAITAD4QoAQAASI1VF0iNTedI/xWBLQAADx9EAACEwA+E
 @echo:DAEAAEGDyP9IjRX9LgAASI1NF0j/Fe4sAAAPH0QAAITAD4TpAAAASI1VF0iNTedI
 @echo:/xVCLQAADx9EAACEwA+EzQAAAEmLBkG5AwAAAEUzwLoeBAAASYvOSItAIP8V/y0A
 @echo:AEyNRedJi85IjRVtLgAASP8VEi0AAA8fRAAATYvGsgFJi83oFP3//4TAdEBJiwZB
 @echo:uQMAAABFM8C6GQQAAEmLzkiLQCD/FbYtAABIjRUfLgAASYvOSP8VzSwAAA8fRAAA
 @echo:/8Y79w+CxP7//7MBSI1N50j/FQEsAAAPH0QAAEiNTRdI/xXxKwAADx9EAABMjZwk
 @echo:oAAAAIrDSYtbIEmLcyhJi3swTYtrOEmL40FfQV5dw8xIjQ3JLQAASP8VeiwAAA8f
 @echo:RAAAx0QkMEsBAABIiUQkKEG5AwAAAEiNBcMtAAC6PAQAAEmLzkiJRCQgRY1B/kj/
 @echo:FTssAAAPH0QAAOlt////zMzMzMzMzMzMSIvESIlYCEiJcBBIiXgYVUFUQVVBVkFX
 @echo:SI1ooUiB7LAAAABMi/lJi/BIjU3PTIviSP8VqSwAAA8fRAAASI1N/0j/FZksAAAP
 @echo:H0QAAEUzwDPSSYvPSP8VNSsAAA8fRAAATIvwSIXAD4TYAgAARTPAM9JIi8hI/xVF
 @echo:LAAADx9EAABIi/hIhcAPhKQCAABBg83/SI0V0SwAAEWLxUiNTc9I/xX7KgAADx9E
 @echo:AAC7AQAAAITAD4QuAgAARYvFSI1N/0mL1Ej/FRArAAAPH0QAAITAD4QQAgAAiFwk
 @echo:KEiNTf+DZCQgAEUzyUWLxTPSSP8VFysAAA8fRAAATIv4SIXAD4TjAQAASIsPSItB
 @echo:GEiLz/8V5isAAITAD4WkAQAARI1jXEUzwEiNVc9Ii89I/xV5KgAADx9EAACEwA+E
 @echo:ggEAAItF54XAD4RfAQAASItF3w+3CGaD+VsPhd4AAABBi9RIjU3PRTPASP8VdyoA
 @echo:AA8fRAAAQTvFD4S/AAAAQYvUSI1Nz0UzwEj/FVgqAAAPH0QAADvDD4ahAAAAZUiL
 @echo:DCVgAAAATYvHM9JIi0kwSP8VoikAAA8fRAAAQYvUSI1Nz0UzwEj/FRwqAAAPH0QA
 @echo:AESLw0iNVc8rw0iNTf9Ei8hI/xUYKgAADx9EAACEwHQtiFwkKEiNTf+DZCQgAEUz
 @echo:yUWLxTPSSP8VAyoAAA8fRAAATIv4SIXAD4WQAAAASI0NWysAAEj/FQwqAAAPH0QA
 @echo:AMdEJDCkAQAA6coAAABMjUV/SI1Vx0iNTc/oXfj//4TAdCdIi01/TYvHD7cBZvfY
 @echo:SBvSSCPRSItNx0j/FQcoAAAPH0QAAIXAdTRIiwZBuQMAAABFM8C6J3cAAEiLzkiL
 @echo:QCD/FWgqAABIjRXRKgAASIvOSP8VfykAAA8fRAAASIsHSIvPSItAGP8VQioAAITA
 @echo:D4Rg/v//SIsHi9NIi89IiwD/FSkqAABJiwaL00mLzkiLAP8VGCoAAOmcAAAASI0N
 @echo:jCoAAEj/FT0pAAAPH0QAAMdEJDCQAQAASIlEJChBuQMAAABIjQWGKgAARIvDujwE
 @echo:AABIiUQkIEiLzkj/Ff8oAAAPH0QAAOtPSYsGugEAAABJi85IiwD/FbQpAABIiwZB
 @echo:uQMAAABFM8C6XBsAAEiLzkiLQCD/FZYpAABNjYcYAgAASIvOSI0VASoAAEj/FaYo
 @echo:AAAPH0QAADLbSI1N/0j/FeQnAAAPH0QAAEiNTc9I/xXUJwAADx9EAABMjZwksAAA
 @echo:AIrDSYtbMEmLczhJi3tASYvjQV9BXkFdQVxdw8zMzMzMzMzMQFVTVldBVEFVQVZB
 @echo:V0iNrCQ49///SIHsyAkAAEiNTCRwSP8VvCcAAA8fRAAASI2NsAYAAEj/FUkoAAAP
 @echo:H0QAAEiNjSABAABI/xWGKAAADx9EAABIjUwkQEj/FXUoAAAPH0QAAEiNjVAGAABI
 @echo:/xX6JwAADx9EAABIjY1wBQAASP8VfycAAA8fRAAASI2NEAUAAEj/FWwnAAAPH0QA
 @echo:AEiNjbAEAABI/xVRKAAADx9EAABIjY1wAgAASP8VPigAAA8fRAAASI2NwAAAAEj/
 @echo:FZsnAAAPH0QAAEiNjRACAABI/xUgJwAADx9EAABIjU1gSP8VeCcAAA8fRAAASI2N
 @echo:sAEAAEj/Ff0mAAAPH0QAAEiNjVAEAABI/xXqJgAADx9EAABIjY3wAwAASP8V1yYA
 @echo:AA8fRAAASI2NkAMAAEj/FcQmAAAPH0QAAEiNjTADAABI/xWxJgAADx9EAABIjY1Q
 @echo:AQAASP8VBicAAA8fRAAASI2N0AIAAEj/FVMmAAAPH0QAAEiNjdAFAABI/xU4JwAA
 @echo:Dx9EAABIjU0wSP8VeCcAAA8fRAAARTPJRTPAM8lBjXEBi9ZI/xX2JAAADx9EAABI
 @echo:/xVKJwAADx9EAAAz/0iFwHQfSP8VNycAAA8fRAAASIvQSIsISItBaEiLyv8VPycA
 @echo:AEj/FRgnAAAPH0QAAEiL2Ej/FUkmAAAPH0QAAEUzyUiNTCRwSIvQTIvDSP8V1yUA
 @echo:AA8fRAAAhMAPhI8FAAC7GQAAAEiNjSABAABEi8NEjXMZQYvWSP8VnSYAAA8fRAAA
 @echo:hMAPhGUFAABEi8NIjUwkQEGL1kj/FX4mAAAPH0QAAITAD4RGBQAASI2VIAEAAEiN
 @echo:jbAGAABI/xUMJgAADx9EAACEwA+EJAUAADPSSI2NsAYAAEj/FQclAAAPH0QAAEGD
 @echo:zf9IjRUnJwAARYvFSI2NcAcAAEj/FQ4lAAAPH0QAAEWLxUiNFQcnAABIjY3QBwAA
 @echo:SP8V8SQAAA8fRAAASI0V8SYAAEiNjbAGAABI/xWnJQAADx9EAAAz0kiNjbAGAABI
 @echo:/xWKJAAADx9EAACEwA+EmgQAAEiNFb4mAABIjY1QBgAASP8VSCUAAA8fRAAAhMAP
 @echo:hHgEAABIjRWgJgAASI2NcAUAAEj/FWYlAAAPH0QAAITAD4RWBAAASI0VgiYAAEiN
 @echo:jRAFAABI/xVEJQAADx9EAACEwA+ENAQAAEiNFXAmAABIjY2wBAAASP8VaiUAAA8f
 @echo:RAAAhMAPhBIEAABIjRVeJgAASI2NcAIAAEj/FUglAAAPH0QAAITAD4TwAwAASI0V
 @echo:TCYAAEiNTWBI/xWhJAAADx9EAACEwA+E0QMAAEiNFTkmAABIjY3AAAAASP8VfyQA
 @echo:AA8fRAAAhMAPhK8DAABIjRUjJgAASI2NsAEAAEj/FZ0kAAAPH0QAAITAD4SNAwAA
 @echo:SI0VCSYAAEiNjRACAABI/xV7JAAADx9EAACEwA+EawMAAEiNFe8lAABIjY1QBAAA
 @echo:SP8VWSQAAA8fRAAAhMAPhEkDAABIjRXZJQAASI2N8AMAAEj/FTckAAAPH0QAAITA
 @echo:D4QnAwAASI0VuyUAAEiNjZADAABI/xUVJAAADx9EAACEwA+EBQMAAEiNFaElAABI
 @echo:jY0wAwAASP8V8yMAAA8fRAAAhMAPhOMCAABIjRWPJQAASI2NUAEAAEj/FZEjAAAP
 @echo:H0QAAITAD4TBAgAARTPASI0VeiUAAEiNjdACAABI/xUUIwAADx9EAACEwA+EnAIA
 @echo:AEiNjdAFAABI/xWhIwAADx9EAACEwA+EgQIAAEiNlVAGAABIjUwkQEj/FaEjAAAP
 @echo:H0QAAITAD4RhAgAASI2VcAUAAEiNTCRASP8VgSMAAA8fRAAAhMAPhEECAABIjZUQ
 @echo:BQAASI1MJEBI/xVhIwAADx9EAACEwA+EIQIAAEiNlbAEAABIjUwkQEj/FUEjAAAP
 @echo:H0QAAITAD4QBAgAASI2VcAIAAEiNTCRASP8VISMAAA8fRAAAhMAPhOEBAABIjVVg
 @echo:SI1MJEBI/xUEIwAADx9EAACEwA+ExAEAAEiNlcAAAABIjUwkQEj/FeQiAAAPH0QA
 @echo:AITAD4SkAQAASI2VsAEAAEiNTCRASP8VxCIAAA8fRAAAhMAPhIQBAABIjZUQAgAA
 @echo:SI1MJEBI/xWkIgAADx9EAACEwA+EZAEAAEiNlVAEAABIjUwkQEj/FYQiAAAPH0QA
 @echo:AITAD4REAQAASI2V8AMAAEiNTCRASP8VZCIAAA8fRAAAhMAPhCQBAABIjZWQAwAA
 @echo:SI1MJEBI/xVEIgAADx9EAACEwA+EBAEAAEiNlTADAABIjUwkQEj/FSQiAAAPH0QA
 @echo:AITAD4TkAAAASI2VUAEAAEiNTCRASP8VBCIAAA8fRAAAhMAPhMQAAABIjZXQAgAA
 @echo:SI1MJEBI/xXkIQAADx9EAACEwA+EpAAAAEiNldAFAABIjUwkQEj/FcQhAAAPH0QA
 @echo:AITAD4SEAAAASI1UJEBIjY2wBgAASP8VVCEAAA8fRAAAhMAPheoCAABEjUvqRTPA
 @echo:utILAABIjUwkcEj/FY8gAAAPH0QAAEiNjbAGAABI/xU0IQAADx9EAABMi8BIjRUZ
 @echo:IgAASI1MJHBIi9hI/xW2IAAADx9EAABIhdt0EUiLC4vWSIsBSIvL/xVzIQAAi/6L
 @echo:94v+SI1NMEj/FdofAAAPH0QAAEiNjSAGAABI/xXHHwAADx9EAABIjY3wBQAASP8V
 @echo:tB8AAA8fRAAASI2N0AUAAEj/FbEfAAAPH0QAAEiNjdACAABI/xWWIAAADx9EAABI
 @echo:jY1QAQAASP8VSyAAAA8fRAAASI2NUAMAAEj/FWgfAAAPH0QAAEiNjTADAABI/xVl
 @echo:HwAADx9EAABIjY2wAwAASP8VQh8AAA8fRAAASI2NkAMAAEj/FT8fAAAPH0QAAEiN
 @echo:jRAEAABI/xUcHwAADx9EAABIjY3wAwAASP8VGR8AAA8fRAAASI2NcAQAAEj/FfYe
 @echo:AAAPH0QAAEiNjVAEAABI/xXzHgAADx9EAABIjY3QAQAASP8V0B4AAA8fRAAASI2N
 @echo:sAEAAEj/Fc0eAAAPH0QAAEiNTWBI/xV9HwAADx9EAABIjY0wAgAASP8Vmh4AAA8f
 @echo:RAAASI2NEAIAAEj/FZceAAAPH0QAAEiNjcAAAABI/xVEHwAADx9EAABIjY2QAgAA
 @echo:SP8VYR4AAA8fRAAASI2NcAIAAEj/FV4eAAAPH0QAAEiNjdAEAABI/xU7HgAADx9E
 @echo:AABIjY2wBAAASP8VOB4AAA8fRAAASI2NMAUAAEj/FRUeAAAPH0QAAEiNjRAFAABI
 @echo:/xUSHgAADx9EAABIjY2QBQAASP8V7x0AAA8fRAAASI2NcAUAAEj/FewdAAAPH0QA
 @echo:AEiNjVAGAABI/xWZHgAADx9EAABIjUwkQEj/FfAeAAAPH0QAAEiNjSABAABI/xXd
 @echo:HgAADx9EAABIjY2wBgAASP8Veh4AAA8fRAAASI1MJHBI/xXJHQAADx9EAACLx0iB
 @echo:xMgJAABBX0FeQV1BXF9eW13DzEiNjbAEAABI/xVvHQAADx9EAABBvgMAAABMjSU9
 @echo:HwAAhMB0MEWLzkiNTCRwRTPAuil3AABI/xWCHQAADx9EAABJi9RIjUwkcEj/FcYd
 @echo:AAAPH0QAAEA4vcQFAAB0NUWLzkiNTCRwRTPAuih3AABI/xVJHQAADx9EAABJi9RI
 @echo:jUwkcEj/FY0dAAAPH0QAAOnq/P//QDi9ZAIAAHUJQDi9BAIAAHQzSI1NYEj/Fc4c
 @echo:AAAPH0QAAITAD4XPBQAASI2NwAAAAEj/FbMcAAAPH0QAAITAD4W0BQAASI1NYEj/
 @echo:FZscAAAPH0QAAITAdBtIjY3AAAAASP8VhBwAAA8fRAAAhMAPhYUFAABIjY1QAQAA
 @echo:SP8VaRwAAA8fRAAAhMB0PUiLjaABAADorOn//0iLjaABAABFM8lFi8VAiHQkKDPS
 @echo:iXwkIEj/FbUcAAAPH0QAAEiL2EiFwHUM6ST8//9IjR3sHgAAQDi9ZAUAAHQPSIvL
 @echo:SP8VERsAAA8fRAAASI2NcAIAAEj/FfYbAAAPH0QAAITAdCOLjcACAABIi9NI/xUF
 @echo:GwAADx9EAACFwHUKuip3AADp3QQAAEA4veQDAAB0Trn2////SP8V5RoAAA8fRAAA
 @echo:SIvISI2VEAkAAEyL+Ej/FZwaAAAPH0QAAIXAdCCLlRAJAAD2wiB1FYHKoAAAAEmL
 @echo:z0j/FZgaAAAPH0QAAEA4vYQDAAB0T7n2////SP8VjhoAAA8fRAAASIvISI2VGAkA
 @echo:AEyL+Ej/FUUaAAAPH0QAAIXAdCGLlRgJAAD2wiB0FoPi30mLzw+66gdI/xVAGgAA
 @echo:Dx9EAABIjY3QBQAASP8VDRsAAA8fRAAAhMAPhNUAAABMjYUoCQAASI2VIAkAAEiN
 @echo:jSAGAADoAur//0yLvSgJAACEwHQnQQ+3B0yLw0iLjSAJAABm99hIG9JJI9dI/xWl
 @echo:GQAADx9EAACFwHUwRYvOSI1MJHBFM8C6J3cAAEj/Fd0aAAAPH0QAAEmL1EiNTCRw
 @echo:SP8VIRsAAA8fRAAASDm9IAkAAHQpZUiLDCVgAAAAM9JMi4UgCQAASItJMEj/FSYa
 @echo:AAAPH0QAAEyLvSgJAABNhf90ImVIiwwlYAAAADPSTIuFKAkAAEiLSTBI/xX4GQAA
 @echo:Dx9EAABIjY3QAgAASP8VHRoAAA8fRAAAhMB0L0iLjSADAABIgcEYAgAA6Fnn//9I
 @echo:i40gAwAATI1EJHBIi9PoZe7//4TAD4Tm+f//QDi9pAQAAHUNQDi9RAQAAA+E+gAA
 @echo:AEiLy0j/FaUYAAAPH0QAAGVIiwwlYAAAADPSRIvARIv4SItJMEj/FXQZAAAPH0QA
 @echo:AEyL4EiFwHVNSI0NgBsAAEj/FTEaAAAPH0QAAMdEJDDJAgAASIlEJChIjUwkcEiN
 @echo:BXsbAABFi85Ei8ZIiUQkILo8BAAASP8V9BkAAA8fRAAA6Uv5//9Fhf90GEyLw0GL
 @echo:10mLzEj/FUUYAAAPH0QAAESL+EHR70yNTCRwQYvXRTPASYvM6Nvm//+EwHUgSI0N
 @echo:/BoAAEj/Fa0ZAAAPH0QAAMdEJDDWAgAA6Xf///9lSIsMJWAAAABNi8Qz0kiLSTBI
 @echo:/xWiGAAADx9EAABAOL0EAgAAdQlAOL1kAgAAdBdMjUQkcDPSSIvL6GDp//+EwA+E
 @echo:rfj//0iNTWBI/xWhGAAADx9EAACEwA+EvQAAAEiLjbAAAADo4OX//0WLxUiNFV4b
 @echo:AABIjU0wSP8VixgAAA8fRAAAhMAPhGf4//9Ii42wAAAASI1VMEj/FbQYAAAPH0QA
 @echo:AIXAdRNIjUwkcOgh6v//hMB1Zuk5+P//SIuNsAAAAEUzyUCIdCQoRYvFM9KJfCQg
 @echo:SP8VmRgAAA8fRAAATI1EJHAz0kiLyEiL2Oiu6P//hMAPhPv3//9Ihdt0HmVIiwwl
 @echo:YAAAAEyLwzPSSItJMEj/FaQXAAAPH0QAAEiNjcAAAABI/xXJFwAADx9EAACEwA+E
 @echo:v/f//0iLjRABAADoCOX//0WLxUiNFYYaAABIjU0wSP8VsxcAAA8fRAAAhMAPhI/3
 @echo://9Ii40QAQAASI1VMEj/FdwXAAAPH0QAAIXAdRdIjUwkcOhJ6f//hMAPhWT3///p
 @echo:Xff//0iLjRABAABFM8lAiHQkKEWLxTPSiXwkIEj/Fb0XAAAPH0QAAEyNRCRwM9JI
 @echo:i8hIi9jo0uf//4TAD4Qf9///SIXbD4QY9///ZUiLDCVgAAAATIvDM9JIi0kwSP8V
 @echo:xBYAAA8fRAAA6fX2//+69AcAAEUzwEiNTCRwRYvOSP8VGxcAAA8fRAAASYvUSI1M
 @echo:JHBI/xVfFwAADx9EAADpvvb//8zMzMzMzMzMzMzMzMxIg+wouE1aAABmOQXw0///
 @echo:dAQzwOtTSGMNH9T//0iNBdzT//9IA8iBOVBFAAB147gLAQAAZjlBGHQeuAsCAABm
 @echo:OUEYdc0zwIO5hAAAAA52GTmB+AAAAOsOM8CDeXQOdgk5gegAAAAPlcC5AQAAAIkF
 @echo:zDMAAOivAwAAi8j/Fc8VAABIiw2QFQAASIPI/0iJBT05AABIiQU+OQAAiwW0MwAA
 @echo:iQFIiw1nFQAAiwWZMwAAiQHoygMAAIM9QzMAAAB1DUiNDboDAAD/FWQVAAAzwEiD
 @echo:xCjDzMzMzMzMzMzMzMzMzEiD7DiLBWYzAABMjQVHMwAARIsNVDMAAEiNFTEzAACJ
 @echo:BT8zAABIjQ0cMwAASI0FMTMAAEiJRCQg/xU6FQAAiQUIMwAASIPEOMPMzMzMzMzM
 @echo:SIlcJAhIiXQkEEiJfCQYQVdIg+wwZUiLBCUwAAAASItYCDP2M8DwSA+xHYE4AAB0
 @echo:G0g7w3UJuwEAAACL8+sSuegDAAD/FQ4UAADr2LsBAAAAiwVhOAAAO8N1DLkfAAAA
 @echo:6N4CAADrZYsFSzgAAIXAdVWJHUE4AABMjT2qFgAASI09ixYAAEiJfCQoiUQkIEk7
 @echo:/3MlhcB1JUiDPwB0EEiLB0iLDUkWAAD/0YlEJCBIg8cISIl8JCjr1oXAdBC4/wAA
 @echo:AOniAAAAiR0oMgAAiwXmNwAAO8N1HUiNFSsWAABIjQ0UFgAA6DUEAADHBcU3AAAC
 @echo:AAAAhfZ1CTPASIcFsDcAAEiDPbg3AAAAdCpIjQ2vNwAA6JoCAACFwHQaRTPAQY1Q
 @echo:AjPJSIsFljcAAEyLDb8VAABB/9FMiwXNMQAASIsVvjEAAIsNsDEAAOh37P//iQWd
 @echo:MQAAgz22MQAAAHUIi8j/FbQTAACDPYkxAAAAdQz/FZUTAACLBXcxAADrLYkFbzEA
 @echo:AIM9iDEAAAB1CYvI/xV+EwAAzIM9WjEAAAB1DP8VZhMAAIsFSDEAAEiLXCRASIt0
 @echo:JEhIi3wkUEiDxDBBX8PMzMzMzMzMzMzMzMzMzMzMzMxIg+wo6GsCAABIg8Qo6R7+
 @echo:///MzMzMzMzMzMzMzMzMzMzMzMzMzGZmDx+EAAAAAABIOw3RMAAAdRBIwcEQZvfB
 @echo://91AcNIwckQ6XIDAADMzMzMzMzMzMzMzMzMzMzMzMxIg+woSIsBgThjc23gdSOD
 @echo:eBgEdR2LSCCNgeD6bOaD+AJ2CIH5AECZAXUH/xV3EgAAzDPASIPEKMPMzMzMzMzM
 @echo:SIPsKEiNDbX/////Fc8RAAAzwEiDxCjDzMzMzMzM/yWkEgAAzMzMzMzMzMxIg+wY
 @echo:M9JIjUH/SIP4/Xc8uE1aAABmOQF1KjlRPHwlgXk8AAAAEHMcSGNBPEgDwUiJBCSB
 @echo:OFBFAABID0XCSIvQSIkEJOsGM9JIiRQkSIvCSIPEGMPMzMzMzMzMzEBTSIPsIIvZ
 @echo:M8n/FUARAABIhcB0KEiLyOiH////SIXAdBu5AgAAAGY5SFx1BIvB6w5mg3hcA7gB
 @echo:AAAAdAKLw0iDxCBbw8zMzMzMzP8l5xEAAMzMzMzMzMwzwMPMzMzMzMzMzMzMzMzM
 @echo:TGNBPEUzyUwDwUyL0kEPt0AURQ+3WAZIg8AYSQPARYXbdB6LUAxMO9JyCotICAPK
 @echo:TDvRcg5B/8FIg8AoRTvLcuIzwMPMzMzMzMzMzMzMzMxIiVwkCFdIg+wgSIvZSI09
 @echo:DM///0iLz+hEAAAAhcB0Ikgr30iL00iLz+iC////SIXAdA+LQCTB6B/30IPgAesC
 @echo:M8BIi1wkMEiDxCBfw8zMzMzMzMzMzMzMzMzMzMzMzMy4TVoAAGY5AXUgSGNBPEgD
 @echo:wYE4UEUAAHURuQsCAABmOUgYdQa4AQAAAMMzwMPMzMzMzMzMSIlcJCBVSIvsSIPs
 @echo:IEiDZRgASLsyot8tmSsAAEiLBXEuAABIO8MPhZMAAABIjU0Y/xWuDwAASItFGEiJ
 @echo:RRD/FbAPAACLwEgxRRD/FZwPAACLwEgxRRD/FYAPAACLwEjB4BhIMUUQ/xVwDwAA
 @echo:i8BIjU0QSDNFEEgzwUiNTSBIiUUQ/xV1DwAAi0UgSLn///////8AAEjB4CBIM0Ug
 @echo:SDNFEEgjwUiLyEg7w3UNSLgzot8tmSsAAEiLyEiJDdUtAABIi1wkSEj30EiJBc4t
 @echo:AABIg8QgXcPMzMzMzMz/JdQPAADMzMzMzMz/JcAPAADMzMzMzMzMzMzMzMzMzMzM
 @echo:wgAAzMzMzMzMzMzMQFNIg+wgSIvZM8n/FfMOAABIi8v/FZoOAAD/FVwPAABIi8i6
 @echo:CQQAwEiDxCBbSP8leA4AAMzMzMzMzMzMzMzMzMzMzMxIiUwkCEiB7IgAAABIjQ0t
 @echo:LgAA/xVvDgAASIsFGC8AAEiJRCRIRTPASI1UJFBIi0wkSP8VSA4AAEiJRCRASIN8
 @echo:JEAAdEJIx0QkOAAAAABIjUQkWEiJRCQwSI1EJGBIiUQkKEiNBdctAABIiUQkIEyL
 @echo:TCRATItEJEhIi1QkUDPJ/xXzDQAA6yNIiwVKLgAASIsASIkFoC4AAEiLBTkuAABI
 @echo:g8AISIkFLi4AAEiLBYcuAABIiQX4LAAASIuEJJAAAABIiQX5LQAAxwXPLAAACQQA
 @echo:wMcFySwAAAEAAADHBdMsAAADAAAAuAgAAABIa8AASI0NyywAAEjHBAECAAAAuAgA
 @echo:AABIa8ABSI0NsywAAEiLFTQsAABIiRQBuAgAAABIa8ACSI0NmCwAAEiLFSEsAABI
 @echo:iRQBuAgAAABIa8AASIsNBSwAAEiJTARouAgAAABIa8ABSIsN+CsAAEiJTARoSI0N
 @echo:3AsAAOhT/v//SIHEiAAAAMPMzMzMzMzMzMzMzMzMzMzMzMzMzMxmZg8fhAAAAAAA
 @echo:/+DMzMzMzMzMzMzMzMzMzEBVSIPsIEiL6kiLAUiL0YsI6Ej7//+QSIPEIF3DzMzM
 @echo:zMzMzMzMzMzMzMzMzMzMzEBVSIPsIEiL6kiLATPJgTgFAADAD5TBi8FIg8QgXcPM
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:YGAAQAEAAAAAYQBAAQAAABgBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAIYABAAQAAAAAAAAAAAAAAAAAAAAAAAAAYRABAAQAAACBEAEABAAAA
 @echo:bEQAQAEAAAAIAAAAAAAAAAB1QQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGBEAEABAAAA
 @echo:AwAAAAAAAABqVwAAAAAAADpXAAAAAAAAJlcAAAAAAAAMVwAAAAAAAPhWAAAAAAAA
 @echo:6FYAAAAAAADOVgAAAAAAALhWAAAAAAAAolYAAAAAAACIVgAAAAAAAHRWAAAAAAAA
 @echo:VlYAAAAAAABOVgAAAAAAAC5VAAAAAAAAGlUAAAAAAAAEVQAAAAAAAOhUAAAAAAAA
 @echo:1lQAAAAAAAC2VAAAAAAAAJpUAAAAAAAAglQAAAAAAABwVAAAAAAAAFJUAAAAAAAA
 @echo:QlQAAAAAAAAsVAAAAAAAAA5UAAAAAAAAVlcAAAAAAAAAAAAAAAAAAC5WAAAAAAAA
 @echo:IlYAAAAAAAAYVgAAAAAAAABWAAAAAAAA9FUAAAAAAADgVQAAAAAAANZVAAAAAAAA
 @echo:zlUAAAAAAADGVQAAAAAAALRVAAAAAAAApFUAAAAAAACWVQAAAAAAAIhVAAAAAAAA
 @echo:AAAAAAAAAABwVQAAAAAAAF5VAAAAAAAAAAAAAAAAAACIUAAAAAAAAOhMAAAAAAAA
 @echo:VlAAAAAAAABAUAAAAAAAACBQAAAAAAAA6E8AAAAAAADMTwAAAAAAAKBTAAAAAAAA
 @echo:XE8AAAAAAAA+TwAAAAAAACBPAAAAAAAA7E4AAAAAAAC6TgAAAAAAAJ5OAAAAAAAA
 @echo:fFMAAAAAAADEUwAAAAAAAOJTAAAAAAAAhk8AAAAAAABUUwAAAAAAADJTAAAAAAAA
 @echo:CFMAAAAAAADmUgAAAAAAAMhSAAAAAAAAqFIAAAAAAAByUgAAAAAAAExSAAAAAAAA
 @echo:LlIAAAAAAAAQUgAAAAAAAORRAAAAAAAAwlEAAAAAAACgUQAAAAAAAGpRAAAAAAAA
 @echo:NlEAAAAAAAAEUQAAAAAAALBPAAAAAAAAxFAAAAAAAAB0TgAAAAAAAFBOAAAAAAAA
 @echo:Ik4AAAAAAAAOTgAAAAAAAPpNAAAAAAAA2k0AAAAAAAC4TQAAAAAAAHZNAAAAAAAA
 @echo:Wk0AAAAAAAAwTQAAAAAAABRNAAAAAAAA/kwAAAAAAAAAAAAAAAAAAHAyAEABAAAA
 @echo:UDQAQAEAAAAAAAAAAAAAAOAsAEABAAAAAAAAAAAAAAAAAAAAAAAAAAAsAEABAAAA
 @echo:oC8AQAEAAAAAAAAAAAAAAKsuAAASMAAAIDEAAAAsAADgLAAAAC8AAGAvAACgLwAA
 @echo:gDAAAHAyAADAMgAAAAAAAAAAAAAgICAgAAAAACVXAABiYXNlXGZzXHV0aWxzXGRv
 @echo:c2tleVxkb3NrZXkuY3h4ACVJNjR4JXgAWwAAAF0AAAAiAAAAIAkAACoAAAAvPwAA
 @echo:L3JlaW5zdGFsbAAAAAAAAC9idWZzaXplPSoAAAAAAAAvbGlzdHNpemU9KgAAAAAA
 @echo:L21hY3JvczoqAAAAL206KgAAAAAAAAAAL21hY3JvcwAvbQAAAAAAAC9oaXN0b3J5
 @echo:AAAAAC9oAAAvaW5zZXJ0AC9vdmVyc3RyaWtlAAAAAAAvZXhlbmFtZT0qAAAAAAAA
 @echo:L21hY3JvZmlsZT0qAAAAAGMAbQBkAC4AZQB4AGUAAABhbGwAAAAAAAAAAAAAAAAA
 @echo:AAAAAPSliIgAAAAAAgAAACMAAAD0RQAA9C8AAAAAAAD0pYiIAAAAAA0AAAAEAgAA
 @echo:GEYAABgwAAAAAAAA9KWIiAAAAAAQAAAAJAAAABxIAAAcMgAAUlNEU3YhuO0UMhi/
 @echo:nPpPZXHdbHYBAAAAZG9za2V5LnBkYgAAR0NUTAAQAABAJAAALnRleHQkbW4AAAAA
 @echo:QDQAACAAAAAudGV4dCRtbiQwMABgNAAAUAAAAC50ZXh0JHgAAEAAACgBAAAucmRh
 @echo:dGEkYnJjAAAoQQAA8AIAAC5pZGF0YSQ1AAAAABhEAAAQAAAALjAwY2ZnAAAoRAAA
 @echo:CAAAAC5DUlQkWENBAAAAADBEAAAIAAAALkNSVCRYQ0FBAAAAOEQAAAgAAAAuQ1JU
 @echo:JFhDWgAAAABARAAACAAAAC5DUlQkWElBAAAAAEhEAAAIAAAALkNSVCRYSUFBAAAA
 @echo:UEQAAAgAAAAuQ1JUJFhJWQAAAABYRAAACAAAAC5DUlQkWElaAAAAAGBEAAAMAAAA
 @echo:LmdlaGNvbnQAAAAAbEQAACQAAAAuZ2ZpZHMAAJBEAABkAQAALnJkYXRhAAD0RQAA
 @echo:TAIAAC5yZGF0YSR6enpkYmcAAABASAAAVAEAAC54ZGF0YQAAlEkAAFAAAAAuaWRh
 @echo:dGEkMgAAAADkSQAAFAAAAC5pZGF0YSQzAAAAAPhJAADwAgAALmlkYXRhJDQAAAAA
 @echo:6EwAAJYKAAAuaWRhdGEkNgAAAAAAYAAAIAAAAC5kYXRhAAAAIGAAAFgGAAAuYnNz
 @echo:AAAAAABwAAAUAQAALnBkYXRhAAAAgAAA8AAAAC5yc3JjJDAxAAAAAPCAAAAQBwAA
 @echo:LnJzcmMkMDIAAAAAIAAAAHYhuO0UMhi/nPpPZXHdbHZcBY3UTfLl3ziGU8r0pYiI
 @echo:AQYCAAYyAjABGwsAG2QYABtUFwAbNBYAGwESABTwEuAQcAAAARgKABhkDAAYVAsA
 @echo:GDQKABhSFPAS4BBwARkKABl0DQAZZAwAGVQLABk0CgAZchXgASMNACPUGwAjdBoA
 @echo:I2QZACM0GAAjARQAGPAW4BRQAAABIw0AI3QeACNkHQAjNBwAIwEWABjwFuAU0BLA
 @echo:EFAAAAEcCgAcATkBDfAL4AnQB8AFcARgAzACUAEEAQAEQgAAAQQBAARiAAAJFQgA
 @echo:FXQKABVkCQAVNAgAFVIR8FoyAAABAAAARS0AAKsuAABgNAAAqy4AAAEGAgAGMgJQ
 @echo:AQAAAAkEAQAEIgAAWjIAAAEAAADcLwAAEjAAAAEAAAASMAAACQoEAAo0BgAKMgZw
 @echo:WjIAAAEAAADtMAAAIDEAAJA0AAAgMQAAAQ0EAA00CQANMgZQAQwCAAwBEQAAAAAA
 @echo:AQAAAGBLAAAAAAAAAAAAAARUAACQQgAA+EkAAAAAAAAAAAAAUFUAAChBAABISwAA
 @echo:AAAAAAAAAAB+VQAAeEIAANhKAAAAAAAAAAAAAEJWAAAIQgAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAABqVwAAAAAAADpXAAAAAAAAJlcAAAAAAAAMVwAAAAAAAPhWAAAAAAAA
 @echo:6FYAAAAAAADOVgAAAAAAALhWAAAAAAAAolYAAAAAAACIVgAAAAAAAHRWAAAAAAAA
 @echo:VlYAAAAAAABOVgAAAAAAAC5VAAAAAAAAGlUAAAAAAAAEVQAAAAAAAOhUAAAAAAAA
 @echo:1lQAAAAAAAC2VAAAAAAAAJpUAAAAAAAAglQAAAAAAABwVAAAAAAAAFJUAAAAAAAA
 @echo:QlQAAAAAAAAsVAAAAAAAAA5UAAAAAAAAVlcAAAAAAAAAAAAAAAAAAC5WAAAAAAAA
 @echo:IlYAAAAAAAAYVgAAAAAAAABWAAAAAAAA9FUAAAAAAADgVQAAAAAAANZVAAAAAAAA
 @echo:zlUAAAAAAADGVQAAAAAAALRVAAAAAAAApFUAAAAAAACWVQAAAAAAAIhVAAAAAAAA
 @echo:AAAAAAAAAABwVQAAAAAAAF5VAAAAAAAAAAAAAAAAAACIUAAAAAAAAOhMAAAAAAAA
 @echo:VlAAAAAAAABAUAAAAAAAACBQAAAAAAAA6E8AAAAAAADMTwAAAAAAAKBTAAAAAAAA
 @echo:XE8AAAAAAAA+TwAAAAAAACBPAAAAAAAA7E4AAAAAAAC6TgAAAAAAAJ5OAAAAAAAA
 @echo:fFMAAAAAAADEUwAAAAAAAOJTAAAAAAAAhk8AAAAAAABUUwAAAAAAADJTAAAAAAAA
 @echo:CFMAAAAAAADmUgAAAAAAAMhSAAAAAAAAqFIAAAAAAAByUgAAAAAAAExSAAAAAAAA
 @echo:LlIAAAAAAAAQUgAAAAAAAORRAAAAAAAAwlEAAAAAAACgUQAAAAAAAGpRAAAAAAAA
 @echo:NlEAAAAAAAAEUQAAAAAAALBPAAAAAAAAxFAAAAAAAAB0TgAAAAAAAFBOAAAAAAAA
 @echo:Ik4AAAAAAAAOTgAAAAAAAPpNAAAAAAAA2k0AAAAAAAC4TQAAAAAAAHZNAAAAAAAA
 @echo:Wk0AAAAAAAAwTQAAAAAAABRNAAAAAAAA/kwAAAAAAAAAAAAAAAAAADsAPz8xRFNU
 @echo:UklOR0BAVUVBQUBYWgAPAD8/MERTVFJJTkdAQFFFQUFAWFoAywFHZXRfU3RhbmRh
 @echo:cmRfSW5wdXRfU3RyZWFtANEAP0luaXRpYWxpemVATE9OR19BUkdVTUVOVEBAUUVB
 @echo:QUVQRUFEQFoAABoAPz8wTE9OR19BUkdVTUVOVEBAUUVBQUBYWgBMAT9RdWVyeVN0
 @echo:cmVhbUBGU05fRklMRUBAUUVBQVBFQVZGSUxFX1NUUkVBTUBAVzRTVFJFQU1BQ0NF
 @echo:U1NAQEtAWgAVAT9QdXRAQVJSQVlAQFVFQUFFUEVBVk9CSkVDVEBAQFoAwAA/SW5p
 @echo:dGlhbGl6ZUBBUlJBWUBAUUVBQUVLS0BaAAA0AD8/MUFSUkFZQEBVRUFBQFhaAAIA
 @echo:Pz8wQVJSQVlAQFFFQUFAWFoA3AA/SW5pdGlhbGl6ZUBSRVNUX09GX0xJTkVfQVJH
 @echo:VU1FTlRAQFFFQUFFWFoAACYAPz8wUkVTVF9PRl9MSU5FX0FSR1VNRU5UQEBRRUFB
 @echo:QFhaAMoAP0luaXRpYWxpemVARkxBR19BUkdVTUVOVEBAUUVBQUVQRUFEQFoAABAA
 @echo:Pz8wRkxBR19BUkdVTUVOVEBAUUVBQUBYWgBwAT9TZXRAU1RSRUFNX01FU1NBR0VA
 @echo:QFVFQUFFS1c0TUVTU0FHRV9UWVBFQEBLQFoAAN8AP0luaXRpYWxpemVAU1RSRUFN
 @echo:X01FU1NBR0VAQFFFQUFFUEVBVlNUUkVBTUBAMDBAWgBOAD8/MVNUUkVBTV9NRVNT
 @echo:QUdFQEBVRUFBQFhaAAAqAD8/MFNUUkVBTV9NRVNTQUdFQEBRRUFBQFhaAABXAT9S
 @echo:ZWFkTGluZUBTVFJFQU1AQFFFQUFFUEVBVldTVFJJTkdAQEVAWgDZAD9Jbml0aWFs
 @echo:aXplQFBBVEhfQVJHVU1FTlRAQFFFQUFFUEVBREVAWgBIAD8/MVBBVEhfQVJHVU1F
 @echo:TlRAQFVFQUFAWFoAIwA/PzBQQVRIX0FSR1VNRU5UQEBRRUFBQFhaAC4BP1F1ZXJ5
 @echo:RmlsZUBTWVNURU1AQFNBUEVBVkZTTl9GSUxFQEBQRUJWUEFUSEBARVBFQUVAWgAA
 @echo:/AA/SXNWYWx1ZVNldEBBUkdVTUVOVEBAUUVBQUVYWgBGAD8/MU9CSkVDVEBAVUVB
 @echo:QUBYWgAAdwE/U2V0Q2FzZVNlbnNpdGl2ZUBBUkdVTUVOVF9MRVhFTUlaRVJAQFFF
 @echo:QUFYRUBaAAAUAT9QcmVwYXJlVG9QYXJzZUBBUkdVTUVOVF9MRVhFTUlaRVJAQFFF
 @echo:QUFFUEVBVldTVFJJTkdAQEBaAAA0AT9RdWVyeUludmFsaWRBcmd1bWVudEBBUkdV
 @echo:TUVOVF9MRVhFTUlaRVJAQFFFQUFQRUFWV1NUUklOR0BAWFoAHAE/UHV0U2VwYXJh
 @echo:dG9yc0BBUkdVTUVOVF9MRVhFTUlaRVJAQFFFQUFYUEVCREBaAACbAD9Eb1BhcnNp
 @echo:bmdAQVJHVU1FTlRfTEVYRU1JWkVSQEBRRUFBRVBFQVZBUlJBWUBAQFoAvwA/SW5p
 @echo:dGlhbGl6ZUBBUkdVTUVOVF9MRVhFTUlaRVJAQFFFQUFFUEVBVkFSUkFZQEBAWgAA
 @echo:MwA/PzFBUkdVTUVOVF9MRVhFTUlaRVJAQFVFQUFAWFoAAAEAPz8wQVJHVU1FTlRf
 @echo:TEVYRU1JWkVSQEBRRUFBQFhaAADgAD9Jbml0aWFsaXplQFNUUklOR19BUkdVTUVO
 @echo:VEBAUUVBQUVQRUFEQFoAAE8APz8xU1RSSU5HX0FSR1VNRU5UQEBVRUFBQFhaACsA
 @echo:Pz8wU1RSSU5HX0FSR1VNRU5UQEBRRUFBQFhaAAgBP01ha2VGaWxlVG9rZW5ATUVT
 @echo:U0FHRUBAU0FfS1BFQkRAWgAAmAA/RGlzcGxheU1zZ0BNRVNTQUdFQEBRRUFBRUtX
 @echo:NE1FU1NBR0VfVFlQRUBAS1BFQkRaWgAAkgA/RGlzcGxheUBNRVNTQUdFQEBRRUFB
 @echo:RVBFQkRaWgDMAUdldF9TdGFuZGFyZF9PdXRwdXRfU3RyZWFtAACcAT9TdHJjYXRA
 @echo:V1NUUklOR0BAUUVBQUVQRUJWMUBAWgAAVAE/UXVlcnlXU1RSQFdTVFJJTkdAQFFF
 @echo:QkFQRUFHS0tQRUFHS0VAWgAAjQA/RGVsZXRlQ2hBdEBXU1RSSU5HQEBRRUFBWEtL
 @echo:QFoAAOoAP0luaXRpYWxpemVAV1NUUklOR0BAUUVBQUVQRUJWMUBLS0BaAADpAD9J
 @echo:bml0aWFsaXplQFdTVFJJTkdAQFFFQUFFUEVCR0tAWgDoAD9Jbml0aWFsaXplQFdT
 @echo:VFJJTkdAQFFFQUFFUEVCREtAWgCeAT9TdHJjaHJAV1NUUklOR0BAUUVCQUtHS0Ba
 @echo:AACpAT9TdHJpY21wQFdTVFJJTkdAQFFFQkFKUEVCVjFAQFoAdWxpYi5kbGwAAOoB
 @echo:R2V0Q29uc29sZUFsaWFzRXhlc0xlbmd0aFcAAPABR2V0Q29uc29sZUFsaWFzZXNX
 @echo:AADaAkdldFN0ZEhhbmRsZQAACQVTZXRDb25zb2xlTnVtYmVyT2ZDb21tYW5kc1cA
 @echo:BgVTZXRDb25zb2xlTW9kZQAA6wFHZXRDb25zb2xlQWxpYXNFeGVzVwAA9gFHZXRD
 @echo:b25zb2xlQ29tbWFuZEhpc3RvcnlXAGsBRXhwdW5nZUNvbnNvbGVDb21tYW5kSGlz
 @echo:dG9yeVcAAwJHZXRDb25zb2xlTW9kZQAA7wFHZXRDb25zb2xlQWxpYXNlc0xlbmd0
 @echo:aFcAAFcDSGVhcFNldEluZm9ybWF0aW9uAAAHAEFkZENvbnNvbGVBbGlhc1cAAPUB
 @echo:R2V0Q29uc29sZUNvbW1hbmRIaXN0b3J5TGVuZ3RoVwBLRVJORUwzMi5kbGwAANUC
 @echo:UnRsQWxsb2NhdGVIZWFwAPgDUnRsRnJlZUhlYXAAbnRkbGwuZGxsAFUAX1hjcHRG
 @echo:aWx0ZXIArgBfYW1zZ19leGl0AAB/AF9fZ2V0bWFpbmFyZ3MAjgBfX3NldF9hcHBf
 @echo:dHlwZQAAMgRleGl0AAAOAV9leGl0AMEAX2NleGl0AACQAF9fc2V0dXNlcm1hdGhl
 @echo:cnIAAH0BX2luaXR0ZXJtAFcAX19DX3NwZWNpZmljX2hhbmRsZXIAACcBX2Ztb2Rl
 @echo:AADSAF9jb21tb2RlAAAvAD90ZXJtaW5hdGVAQFlBWFhaAG1zdmNydC5kbGwAAIsF
 @echo:U2xlZXAAewVTZXRVbmhhbmRsZWRFeGNlcHRpb25GaWx0ZXIAfwJHZXRNb2R1bGVI
 @echo:YW5kbGVXAABOBFF1ZXJ5UGVyZm9ybWFuY2VDb3VudGVyAB8CR2V0Q3VycmVudFBy
 @echo:b2Nlc3NJZAAjAkdldEN1cnJlbnRUaHJlYWRJZAAA8QJHZXRTeXN0ZW1UaW1lQXNG
 @echo:aWxlVGltZQAPA0dldFRpY2tDb3VudAAA0gRSdGxDYXB0dXJlQ29udGV4dADZBFJ0
 @echo:bExvb2t1cEZ1bmN0aW9uRW50cnkAAOAEUnRsVmlydHVhbFVud2luZAAAvAVVbmhh
 @echo:bmRsZWRFeGNlcHRpb25GaWx0ZXIAAB4CR2V0Q3VycmVudFByb2Nlc3MAmgVUZXJt
 @echo:aW5hdGVQcm9jZXNzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AQAAAAAAAAAyot8tmSsAAM1dINJm1P//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIEAAAbBAAAEBIAAB0EAAA
 @echo:xREAAEhIAADMEQAAVRMAAGRIAABcEwAAihQAAHxIAACQFAAAHxcAAJRIAAAoFwAA
 @echo:7RoAALRIAAD0GgAA8ysAANRIAAAALAAA0ywAAOxIAADgLAAAKS0AAPRIAAAwLQAA
 @echo:7i4AAPxIAAAALwAAEi8AAOxIAAAwLwAATi8AADBJAABgLwAAmS8AAOxIAACgLwAA
 @echo:uC8AAOxIAADMLwAAIDAAADRJAAAoMAAAbTAAAEBIAADgMAAALTEAAFRJAAB0MQAA
 @echo:SDIAAHhJAAB8MgAAsDIAAEBIAADAMgAAMTQAAIRJAABQNAAAUjQAAJBJAABgNAAA
 @echo:fjQAAChJAACQNAAAsDQAAChJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAgDoAACAKAAAgBAAAABAAACA
 @echo:GAAAAFgAAIAAAAAAAAAAAAAAAAAAAAEAAQAAAHAAAIAAAAAAAAAAAAAAAAAAAAEA
 @echo:AQAAAIgAAIAAAAAAAAAAAAAAAAAAAAEAAQAAAKAAAIAAAAAAAAAAAAAAAAAAAAEA
 @echo:CQQAALgAAAAAAAAAAAAAAAAAAAAAAAEACQQAAMgAAAAAAAAAAAAAAAAAAAAAAAEA
 @echo:CQQAANgAAAA4hwAAyAAAAAAAAAAAAAAAoIMAAJgDAAAAAAAAAAAAAPCAAACqAgAA
 @echo:AAAAAAAAAAADAE0AVQBJADw/eG1sIHZlcnNpb249IjEuMCIgZW5jb2Rpbmc9IlVU
 @echo:Ri04IiBzdGFuZGFsb25lPSJ5ZXMiPz4NCjwhLS0gQ29weXJpZ2h0IChjKSBNaWNy
 @echo:b3NvZnQgQ29ycG9yYXRpb24gLS0+DQo8YXNzZW1ibHkgeG1sbnM9InVybjpzY2hl
 @echo:bWFzLW1pY3Jvc29mdC1jb206YXNtLnYxIiBtYW5pZmVzdFZlcnNpb249IjEuMCI+
 @echo:DQo8YXNzZW1ibHlJZGVudGl0eQ0KICAgIHZlcnNpb249IjUuMS4wLjAiDQogICAg
 @echo:cHJvY2Vzc29yQXJjaGl0ZWN0dXJlPSJhbWQ2NCINCiAgICBuYW1lPSJNaWNyb3Nv
 @echo:ZnQuV2luZG93cy5GaWxlc3lzdGVtLkRvc0tleSINCiAgICB0eXBlPSJ3aW4zMiIN
 @echo:Ci8+DQo8ZGVzY3JpcHRpb24+S2V5Ym9hcmQgSGlzdG9yeSBVdGlsaXR5PC9kZXNj
 @echo:cmlwdGlvbj4NCg0KPHRydXN0SW5mbyB4bWxucz0idXJuOnNjaGVtYXMtbWljcm9z
 @echo:b2Z0LWNvbTphc20udjMiPg0KICAgIDxzZWN1cml0eT4NCiAgICAgICAgPHJlcXVl
 @echo:c3RlZFByaXZpbGVnZXM+DQogICAgICAgICAgICA8cmVxdWVzdGVkRXhlY3V0aW9u
 @echo:TGV2ZWwNCiAgICAgICAgICAgICAgICBsZXZlbD0iYXNJbnZva2VyIg0KICAgICAg
 @echo:ICAgICAgICAgIHVpQWNjZXNzPSJmYWxzZSINCiAgICAgICAgICAgIC8+DQogICAg
 @echo:ICAgIDwvcmVxdWVzdGVkUHJpdmlsZWdlcz4NCiAgICA8L3NlY3VyaXR5Pg0KPC90
 @echo:cnVzdEluZm8+DQo8L2Fzc2VtYmx5Pg0KDQoAAAAAAACUAzQAAABWAFMAXwBWAEUA
 @echo:UgBTAEkATwBOAF8ASQBOAEYATwAAAAAAvQTv/gAAAQAAAAoANA5hSgAACgA0DmFK
 @echo:PwAAAAAAAAAEAAQAAQAAAAAAAAAAAAAAAAAAAPQCAAABAFMAdAByAGkAbgBnAEYA
 @echo:aQBsAGUASQBuAGYAbwAAANACAAABADAANAAwADkAMAA0AEIAMAAAAEwAFgABAEMA
 @echo:bwBtAHAAYQBuAHkATgBhAG0AZQAAAAAATQBpAGMAcgBvAHMAbwBmAHQAIABDAG8A
 @echo:cgBwAG8AcgBhAHQAaQBvAG4AAABaABkAAQBGAGkAbABlAEQAZQBzAGMAcgBpAHAA
 @echo:dABpAG8AbgAAAAAASwBlAHkAYgBvAGEAcgBkACAASABpAHMAdABvAHIAeQAgAFUA
 @echo:dABpAGwAaQB0AHkAAAAAAG4AJwABAEYAaQBsAGUAVgBlAHIAcwBpAG8AbgAAAAAA
 @echo:MQAwAC4AMAAuADEAOQAwADQAMQAuADMANgAzADYAIAAoAFcAaQBuAEIAdQBpAGwA
 @echo:ZAAuADEANgAwADEAMAAxAC4AMAA4ADAAMAApAAAAAAAuAAcAAQBJAG4AdABlAHIA
 @echo:bgBhAGwATgBhAG0AZQAAAGQAbwBzAGsAZQB5AAAAAACAAC4AAQBMAGUAZwBhAGwA
 @echo:QwBvAHAAeQByAGkAZwBoAHQAAACpACAATQBpAGMAcgBvAHMAbwBmAHQAIABDAG8A
 @echo:cgBwAG8AcgBhAHQAaQBvAG4ALgAgAEEAbABsACAAcgBpAGcAaAB0AHMAIAByAGUA
 @echo:cwBlAHIAdgBlAGQALgAAAD4ACwABAE8AcgBpAGcAaQBuAGEAbABGAGkAbABlAG4A
 @echo:YQBtAGUAAABEAE8AUwBLAEUAWQAuAEUAWABFAAAAAABqACUAAQBQAHIAbwBkAHUA
 @echo:YwB0AE4AYQBtAGUAAAAAAE0AaQBjAHIAbwBzAG8AZgB0AK4AIABXAGkAbgBkAG8A
 @echo:dwBzAK4AIABPAHAAZQByAGEAdABpAG4AZwAgAFMAeQBzAHQAZQBtAAAAAABEABAA
 @echo:AQBQAHIAbwBkAHUAYwB0AFYAZQByAHMAaQBvAG4AAAAxADAALgAwAC4AMQA5ADAA
 @echo:NAAxAC4AMwA2ADMANgAAAEQAAAABAFYAYQByAEYAaQBsAGUASQBuAGYAbwAAAAAA
 @echo:JAAEAAAAVAByAGEAbgBzAGwAYQB0AGkAbwBuAAAAAAAJBLAEAAAAAM3+zf7IAAAA
 @echo:AAABAAAAAAARAAAAAAAAAAIAAAA+EPlZ+2S9icHVmtFwZwB2U3vBAn7rslvC1BSG
 @echo:5B5rYgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIgAAAAOAAAAmAAAAAgAAACgAAAA
 @echo:DgAAALAAAAAEAAAAAAAAAAAAAAC4AAAADAAAAAAAAABNAFUASQAAAAAAAAAAAAAA
 @echo:EAAAABgAAABNAFUASQAAAAAAAAAAAAAAEAAAAAAAAABlAG4ALQBVAFMAAAAAAAAA
 @echo:AEAAACAAAAAAoAigaKCAoIigkKAYoRikIKQwpEikUKQAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
 @echo:-----END CERTIFICATE-----
 @goto:EOF


::====================================================================::


:encodeFindstrExe -- Derived from the original source.
 @echo:off
 @echo:-----BEGIN CERTIFICATE-----
 @echo:TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAA8AAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5v
 @echo:dCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAADtv7C7qd7e6Kne3uip3t7o
 @echo:oKZN6IPe3ui9tdvpq97e6L213emq3t7oqd7f6MXe3ui9td/prN7e6L211ums3t7o
 @echo:vbXa6b3e3ui9tSHoqN7e6L213Omo3t7oUmljaKne3ugAAAAAAAAAAAAAAAAAAAAA
 @echo:UEUAAGSGBwBxWS0NAAAAAAAAAADwACIACwIOFABWAAAAygAAAAAAAFBbAAAAEAAA
 @echo:AAAAQAEAAAAAEAAAAAIAAAoAAAAKAAAACgAAAAAAAAAAcAEAAAQAAD4oAQADAGDB
 @echo:AAAIAAAAAAAAoAAAAAAAAAAAEAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAA
 @echo:CH8AAOABAAAAUAEACAgAAAAwAQDoAgAAAAAAAAAAAAAAYAEAUAAAAKB3AABUAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQHAAABgBAAAAAAAAAAAAAFhxAADYAwAA
 @echo:lH4AAEAAAAAAAAAAAAAAAAAAAAAAAAAALnRleHQAAADaVAAAABAAAABWAAAABAAA
 @echo:AAAAAAAAAAAAAAAAIAAAYC5yZGF0YQAAMh4AAABwAAAAIAAAAFoAAAAAAAAAAAAA
 @echo:AAAAAEAAAEAuZGF0YQAAAPCXAAAAkAAAAAIAAAB6AAAAAAAAAAAAAAAAAABAAADA
 @echo:LnBkYXRhAADoAgAAADABAAAEAAAAfAAAAAAAAAAAAAAAAAAAQAAAQC5kaWRhdAAA
 @echo:EAAAAABAAQAAAgAAAIAAAAAAAAAAAAAAAAAAAEAAAMAucnNyYwAAAAgIAAAAUAEA
 @echo:AAoAAACCAAAAAAAAAAAAAAAAAABAAABALnJlbG9jAABQAAAAAGABAAACAAAAjAAA
 @echo:AAAAAAAAAAAAAAAAQAAAQgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAMzMzMzMzMzMSIlcJAhIiXQkEFdIg+wgSIsaSIvySIv5
 @echo:xkQkQQDptgAAADwFD4S4AAAASP/DD7bIg+kBdHuD6QF0Q4PpAXQag/kBD4WQAAAA
 @echo:gD8NdAWAPwp1JjPA6Y8AAABED7YHugEAAABBi8hJwegDg+EH0+JBhBQYdN5Ig8Mg
 @echo:SP/H61sPtg9I/8eDPfp/AAAAdRiITCRASI1MJEBI/xXMYgAADx9EAAAPtggPtgNI
 @echo:/8M7yHWk6yhED7YDSI1TAUiLBRkUAQBIi8//FWhkAACFwHWGD7YDSP/DSAP4SAPY
 @echo:igOEwA+FQP///0iJHkiLx0iLXCQwSIt0JDhIg8QgX8PMzMzMzMzMzEyL3EmJWwhJ
 @echo:iXMgSYlTEFdIg+wgigJIi9mEwHQaPAV0FkmNUxDo1v7//0iL2EiFwHQ3SItUJDiA
 @echo:OgBIjXIBdEnGRCRBAEiNBSxlAAAPtg5IYzyISAP+g+kCD4SeAAAAg+kBdFqD+QF0
 @echo:ETPA6yGAOw1094A7CnTySP/DSIvXSIvL6Hv///+FwHTkuAEAAABIi1wkMEiLdCRI
 @echo:SIPEIF/DzEQPtgO6AQAAAEGLyEnB6AOD4QfT4kGEVDABdK5I/8NIi9dIi8voN///
 @echo:/4XAdNLruooDSP/Dgz2pfgAAAHUXSI1MJECIRCRASP8Ve2EAAA8fRAAAigA6RgEP
 @echo:hWz///9Ii9dIi8vo+P7//4XAdMPpeP///8zMzMzMzMxIiVwkCEUPttBJweoDRQ+2
 @echo:2EwD0UGD4wdFOsF3dEiNHBFFhdt1JkEPtsiDwQhBD7bBO8h3F0w703Mti0QkKPfY
 @echo:sAgayUGICkn/wus9TDvTcxZBD74SQYvLikQkKEQPs9rS4ArQQYgSQYP7B0mNQgFB
 @echo:jUsBSQ9FwkyL0EGLw0Uz24P4B7ABRA9F2UQCwEU6wXaQSItcJAjDzMzMzMzMzMzM
 @echo:SIvESIlYEEiJcBhIiXggVUFUQVVBVkFXSI2oiP7//0iB7FACAABIiwVrfQAASDPE
 @echo:SImFQAEAAEUz5EiL+UQ5JYh9AABEiGQkMUSIZCQ5RIhkJDV1EkiDyv9I/8JEOCQR
 @echo:dffoHT4AAIoHSI10JEBBvQEAAAA8XnUOSQP9iEQkQEiNdCRBigeEwA+EdwMAAEG3
 @echo:XEiNhT4BAABIO/APh9kDAABIjRUMYwAASIvPQb7+////SP8VEGEAAA8fRAAASIvI
 @echo:SJhEODw4dThEi/FEOGQ4AQ+EoAMAAI1ZAkhjy0iNFdFiAABIA89I/xXbYAAADx9E
 @echo:AAADw0hjyEiLwUQ4PDl0yEhjwYA8OCp1F4vBQSvNhcAPhGADAACNQf9EO/BBD0TO
 @echo:hcl+eUE7zXRbg/kCdQVEOD90UUyNRgFEiC5JjXABigdBOsd1A0kD/UE6x0GL1EiN
 @echo:hT8BAAAPlcKDwv4D0Ug78A+HFAMAAIoHi8qIBkkD/UkD9YXSf8hAisZBKsBBKsVB
 @echo:iADrGYoHxgYCQTrHdQVJA/2KB4hGAUiDxgJJA/1IjYU9AQAASDvwD4fNAgAAigeE
 @echo:wA+ETgIAADwudRxJA/2APyp1CUkD/cYGBUkD9cYGBEkD9eklAgAAPFsPhf8BAABJ
 @echo:A/2KB4TAD4SKAgAAxgYDD1fASP/GRYv9DxEGDxFGEDxeD4WiAQAAZg9vBcFiAABI
 @echo:jZ1AAQAAQbENRIlkJCAPEQZIK95FisFIi9NIi85JA/0PEUYQ6Cf9//9BsQpEiWQk
 @echo:IEWKwUiL00iLzugR/f//RYv86VABAACEwA+EFwIAADxcdQ1JA/2KB4TAD4QGAgAA
 @echo:SQP9TIvHgD8tdSeKTwGEyXQggPlddBtI/8eA+Vx1DkmNUAJEOCJ0BYoKSIv6SQP9
 @echo:6wKKyIhMJDhIjVQkOEiNTCQ0iEQkNEj/FWNfAAAPH0QAAIXAD4/dAAAAQYvcSI1U
 @echo:JDCIXCQwSI1MJDRI/xU+XwAADx9EAACFwA+PqQAAAEiNVCQ4SI1MJDBI/xUgXwAA
 @echo:Dx9EAACFwA+PiwAAAESKTCQwTI21QAEAAEwr9kSJfCQgSYvWRYrBSIvO6DH8//9E
 @echo:OSWWegAAdWCLy0j/Fc9dAAAPH0QAAIXAdBNIjUwkMEj/FfJdAAAPH0QAAOsji8tI
 @echo:/xXKXQAADx9EAACFwHQpSI1MJDBI/xU1XQAADx9EAABEikwkMEmL1kWKwUSJfCQg
 @echo:SIvO6Mj7//9BA92B+wABAAAPgib///+KBzxdD4Wm/v//SQP9gD8qdRxBuCEAAABI
 @echo:jVb/SIvO6DdNAADGRv8FSQP1SQP9SIPGIEG3XOsexgYFSQP1xgYCQTrHdQVJA/2K
 @echo:B4hGAUiDxgJIg8cCRDgnD4WM/P//RIgmSI1EJEBJA/Ur8IvOi/5I/xWjXAAADx9E
 @echo:AABIi9hIhcB1COhdDwAASIvYTGPHSI1UJEBIi8vowEwAAEiLw0iLjUABAABIM8zo
 @echo:bEQAAEyNnCRQAgAASYtbOEmLc0BJi3tISYvjQV9BXkFdQVxdw8wzwOvLuRAAAADo
 @echo:zA4AAMzMzMzMzMzMSIvESIlYCEiJaBBIiXAYSIl4IEFXSIPsMIA5XkiNWQEPV8BI
 @echo:i/pID0XZDxECSIvrDxFCEIoDhMAPhOoAAABBvyAAAAAz9jwFdQpI/8O+AQAAAIoD
 @echo:SIvTD7bISP/DhMB0JYPpAQ+EgwAAAIPpAQ+EiAAAAIPpAXRdg+kBdBuD+QEPhZEA
 @echo:AAC5AgAAAEj/FXpcAAAPH0QAAMxmD28FpF8AAEGxDYNkJCAARYrBDxEHSYvXSIvP
 @echo:DxFHEOgX+v//g2QkIABBsQpFisFJi9dIi8/oAfr//+tCSIvPSYvXigNI/8MIAUj/
 @echo:wUiD6gF18OsqhfZ1lYoDSI1aAoTAdItEigtJi9dFisHHRCQgAQAAAEiLz+jA+f//
 @echo:SP/DhfZ0DYoDSIvrhMAPhRz///9Ii1wkQEiLxUiLbCRISIt0JFBIi3wkWEiDxDBB
 @echo:X8PMzMzMzMzMzMzMzMzMzEg7ykgbwEgjwcPMzMzMzMzMzMzMSIlcJBhVVldBVkFX
 @echo:SI1sJNBIgewwAQAASIsFhXcAAEgzxEiJRSBIY9pMi/GD+wIPjKkAAACAOVwPhaAA
 @echo:AACAeQE8D4WWAAAA9gV9hQAACI1D/khj+L4AAQAAdVJIjUcNSDvGD4cyAQAAiwVd
 @echo:dwAASI1MJC3yDxAFSHcAAEmDxgKJRCQoTIvHigVDdwAASYvWiEQkLPIPEUQkIOhj
 @echo:SgAAjVMLSI1MJCDoAAEAAOsESYPGAkiNRwFIO8YPh9wAAACKBfd2AABIjUwkIUyL
 @echo:x4hEJCBJi9boKUoAAOmMAAAA9gXnhAAAEI1D/khj+L4AAQAAdVFIjUcNSDvGD4ec
 @echo:AAAATIvHSI1MJCBJi9bo80kAAPIPEAWtdgAAjVML8g8RRBweSI1MJCCLBaF2AABM
 @echo:i/uJRBwmigWYdgAAiEQcKuhrAAAA6wNMi/tIjUcBSDvGd0xMi8dIjUwkIEmL1uij
 @echo:SQAAigVbdgAAQohEPB6NU/9IjUwkIOg1AAAASItNIEgzzOhJQQAASIucJHABAABI
 @echo:gcQwAQAAQV9BXl9eXcPMuQIAAADotwsAAMzMzMzMzMxIiVwkGEiJdCQgVVdBVUFW
 @echo:QVdIjWwkoEiB7GABAABIiwXTdQAASDPESIlFUEyNPQ3+//9IY9pMOT1TCgEAdERE
 @echo:i8NIi9FBs1yD+wJ8C0Q4GXUGgHkBPHQkhdt+UIoCQf/ISP/CQTrDdQ5Bg+gBdQWA
 @echo:Oj50CEj/wkWFwOvei9Po0f3//0iLTVBIM8zokUAAAEyNnCRgAQAASYtbQEmLc0hJ
 @echo:i+NBX0FeQV1fXcPMRIsFbYMAAESNS/9Bg8gIxkQkIQCAOV5ED0UFVYMAADPSRI1S
 @echo:/kWFyX4VSGPCRDgcCHUFRIvS/8L/wkE70XzrQYv4hdt+FYB8C/8kdQ6NQ/5EO9B0
 @echo:BkGL2YPPEIH7/gAAAA+PyAEAAEyLwUhj80G+AAEAAEiNTCRQTIvOQYvWSP8Vz1cA
 @echo:AA8fRAAAQPbHEHQHxkQ0UA3/w0hjw0k7xg+DhgEAAEiNTCRQxkQEUADoAvf//0yL
 @echo:8EiFwA+EGf////8FKAkBAED2xwh1EEiNVCQoSIvI6Gn7//9Mi/BIjVQkKEmLzuhZ
 @echo:+///gDgAdQxMiT3xCAEA6d/+//8z20yNLfPj//9MY/uLy0mLx4PhB0jB+AMPvkQE
 @echo:KA+jyA+DzwAAALkQAAAASP8VSlcAAA8fRAAASIvwSIXAdQjoBAoAAEiL8EMPtrwv
 @echo:ACUBAEyJdgiF/w+FgwAAAEhjPSF0AACNRwGJBRh0AACB/wABAAAPjZAAAABJg6T9
 @echo:gJYAAACDPQB0AAAAQ4i8LwAlAQB1TYvLSP8VwVcAAA8fRAAAhcB0O0iNTCQgiFwk
 @echo:IEj/FVBXAAAPH0QAADgYdRVIjUwkIEj/FaNWAAAPH0QAADgYdA0PtkQkIEKIvCgA
 @echo:JQEASGPPSYuEzYCWAABIiQZJibTNgJYAAP/DgfsAAQAAD43c/f//6QH///+7AgAA
 @echo:AIvL6GBEAABIi8iNUwhFM8Do6jgAAIvLSP8VKVcAAA8fRAAAzOgeQAAAzLkCAAAA
 @echo:6MsIAADMzMzMzMzMzMzMzEiJVCQQU1ZXQVRBVkFXSIPsOEiL8kiL2UyL8UiJjCSA
 @echo:AAAATI0lhuL//0g73g+D3gAAAA+2A0IPtowgACUBAEj/w0yL+0iJXCQohMl03EmL
 @echo:vMyAlgAASIX/dRCNTwJI/xWjVgAADx9EAADMSP/LSIlcJHBIhf8PhI0AAABIi1cI
 @echo:SIs/SIm8JIgAAACAOl51Dkj/wkk73nYGgHv/CnXVSIsFg1UAAEiJBeQGAQCDPYly
 @echo:AAAASA9EBY1VAABIiQXOBgEASIvL6O7y//+JRCQg6ywzwIlEJCBMjSXT4f//SIt0
 @echo:JHhIi1wkcEyLtCSAAAAASIu8JIgAAABMi3wkKIXAD4Rv////SIvD6wpJi9/pGf//
 @echo:/zPASIPEOEFfQV5BXF9eW8PMzMzMzMzMSIvESIlYCEiJaBBIiXAYSIl4IEFUQVZB
 @echo:V0iD7CBIiwVMBgEASIPL/8YBAE2L4EyL+UiL+0yLMEw78HRVSYvuSY1OIEj/x4A8
 @echo:OQB19//HvgUBAADrNkyLwUiL1kmLz0j/FdtUAAAPH0QAAEg7Lf8FAQB0RUmLLkiL
 @echo:w0yL9UiNTSBI/8CAPAEAdfcD+Dv+d3DrxEyNQCBI/8dBgDw4AHX2/8e+BQEAADv+
 @echo:d1WL1kj/FZVUAAAPH0QAAEj/w0GAPBwAdfaLx0gD2Eg73nczTYvESIvWSYvPSItc
 @echo:JEBIi2wkSEiLdCRQSIt8JFhIg8QgQV9BXkFcSP8lRlQAAMzMzMzMuQIAAADojwYA
 @echo:AMzMzMzMzMxIiVwkEFVWV0FUQVVBVkFXSI2sJAD7//9IgewABgAASIsFqnAAAEgz
 @echo:xEiJhfAEAABIix0pBQEASIPO/0Uz/01j4UyJRCRoTYvoSIlMJFhIi/lIhdsPhSMC
 @echo:AAC5LQEAAEj/FZJTAAAPH0QAAEiJBe4EAQBIi9hIhcAPhNcFAABJacwQAQAASP8V
 @echo:bFMAAA8fRAAASIlDGEiFwHUXSIvLSP8V1FMAAA8fRAAASAvG6aYFAABBvgABAABE
 @echo:iHsgTIl0JEBIjYXwAgAASIlEJDhMjY3wAwAASI2F8AEAAEiJcxBIiVsISI1UJFBI
 @echo:iRtBuAMAAABJi00ATIl0JDBIiUQkKEyJdCQgSP8VHlMAAA8fRAAASIsNSgQBAEGN
 @echo:XgZIg8EgTI1EJFCL00j/FQxTAAAPH0QAAEiLDSgEAQBMjYXwAwAASIPBIIvTSP8V
 @echo:5FIAAA8fRAAASYtNAEiL3kj/w0Q4PBl190yNhfABAABIjVMBSP8VxVIAAA8fRAAA
 @echo:SYtNAEyNhfACAABIjVMBSP8VolIAAA8fRAAASYP8AQ+OpAAAAL8BAAAASYtM/QBI
 @echo:jYXwAgAATIl0JEBMjY3wAwAASIlEJDhIjVQkUEiNhfABAABMiXQkMEiJRCQoQbgD
 @echo:AAAATIl0JCBI/xVBUgAADx9EAABJi0z9AEiL3kj/w0Q4PBl190yNhfABAABIjVMB
 @echo:SP8VKVIAAA8fRAAASYtM/QBMjYXwAgAASI1TAUj/FQVSAAAPH0QAAEj/x0k7/A+M
 @echo:Zv///0iLfCRYSIsdGAMBAE2F5H4nSYvPSYvUSItDGEiJNAFIjYkQAQAASItDGESI
 @echo:vAH6/v//SIPqAXXfSIXbD4TYAwAASItLEEg7znUwTI0Fg1QAAEiLz+hb/P//SI1U
 @echo:JHBIi89I/xXkTwAADx9EAABIix2wAgEASIlDEOsgSI1UJHBI/xWWTwAADx9EAABI
 @echo:ix2SAgEAhcAPhMECAABIOXMQD4S3AgAA9kQkcBAPhA4BAABEOb1gBQAAD4SMAgAA
 @echo:gH2cLopFnXUchMAPhHsCAACAfZwudQ48LnUKRDh9ng+EZwIAALktAQAASP8Vz1AA
 @echo:AA8fRAAASIv4SIXAD4RKAgAASWnMEAEAAEj/FbBQAAAPH0QAAEiJRxhIhcB1FEiL
 @echo:z0j/FRhRAAAPH0QAAOkaAgAATI1FnLoGAQAASI1PIEj/FbpQAAAPH0QAAEyNBYpT
 @echo:AAC6BgEAAEiNTyBI/xWWUAAADx9EAABMiwW6AQEASIl3EEmLAEiJB0yJRwhNheR+
 @echo:J0mLz0mL1EiLRxhIiTQBSI2JEAEAAEiLRxhEiLwI+v7//0iD6gF130mJOEiL30iL
 @echo:B0iJHXABAQBIiXgI6YsBAABMi3sYRYv0RYXkD454AQAASWncEAEAAE+NbOUASQPf
 @echo:M/9IjZvw/v//Qf/OTY1t+Eg5O0APlcdIOTN1ck2LRQBIi0wkWOiu+v//SItMJFhI
 @echo:jZWwAAAASP8VM04AAA8fRAAAM//GQwgASDvGSIkDQA+Vxw+EkQAAAEljxkyNhdwA
 @echo:AABIacgQAQAAugQBAABIg8EKSQPPSP8VpE8AAA8fRAAAioWwAAAAJBCIQwnrW4B7
 @echo:CAB0VUiLC0iNlbAAAABI/xWbTQAADx9EAADGQwgAi/iFwHRISWPOTI2F3AAAAEhp
 @echo:yRABAAC6BAEAAEiDwQpJA89I/xVITwAADx9EAACKjbAAAACA4RCISwmF/3QPgHsJ
 @echo:AHQqxkMIAekb////SIsLSIXJdBVIO850DEj/FUhNAAAPH0QAAEiDIwDGQwgAhf90
 @echo:M01jzkiNRZxNacEQAQAASYPACk0Dx0wrwA+2CEIPthQAK8p1B0j/wIXSde2FyQ+E
 @echo:xwAAAEWF9g+Po/7//0iLHeT/AABMi2wkaEUz/0iF2w+EyAAAAEiLfCRY6eb8//9I
 @echo:i0sQSDvOdBNI/xXJTAAADx9EAABIix2t/wAASItDCEiL+0iJBZ//AABIi9hIO8d0
 @echo:D0iLB0iJA0iLB0iJWAjrCkmL30iJHX7/AABMi3cYTYXkfjRJi9xJiw5IjUH/SIP4
 @echo:/XcMSP8VbkwAAA8fRAAASYHGEAEAAEiD6wF12kyLdxhIix1B/wAASYvOSP8VT04A
 @echo:AA8fRAAA6SP9//9Ii0wkWEyNRZxJadEQAQAAQsZEOggB6KL4//+4AQAAAOsCi8ZI
 @echo:i43wBAAASDPM6JI1AABIi5wkSAYAAEiBxAAGAABBX0FeQV1BXF9eXcPMzMzMzMzM
 @echo:QFNIg+wgi9m5AgAAAOhWOwAATIsFb34AAEiLyIvT6N0vAAC5AgAAAEj/FRlOAAAP
 @echo:H0QAAMzMzMzMzMzMSIPsKLkCAAAA6B47AABMiwU3fgAASIvIugIAAADooi8AALkC
 @echo:AAAASP8V3k0AAA8fRAAAzMzMzMzMzMzMSIXJdEVTSIPsIEiL2UiLSwhIhcl0B+jl
 @echo:////6wb/DU3+AABIi8tIixtIY0EQSCvISIPh+Ej/FT1NAAAPH0QAAEiF23XISIPE
 @echo:IFvDzMzMzMzMzMzMSIvESIlYCEiJaBBIiXAYSIl4IEFWSIPsIEhj8rgIAAAARIvG
 @echo:TIvxQYPgB0ErwEH32I1WGBvbI9iD+hhyc41GGAPDO8JyaovIi+hI/xVTTAAADx9E
 @echo:AABIi/hIhcB1COgN////SIv4SGPDTIvOSAP4TYvGSIvPSIvVSP8VBUwAAA8fRAAA
 @echo:SItcJDBIjQQ+SIMgAEiDYAgASItsJDhIi3wkSIlwEEiLdCRASIPEIEFew8y5EAAA
 @echo:AOh6/v//zMzMzMzMzMzMzEiJXCQISIl0JBBXSIPsIItBEEiL2UErwElj+AEFx3YA
 @echo:AEyLykhjQRBIi/FIK9hEiUEQSIPj+EH2wAd0EUiL17kIAAAAg+IHSCvKSAPZTIvH
 @echo:SYvRSIvL6Mc7AABIA99BuBgAAABIi8tIi9boszsAAEiLdCQ4SIvDSItcJDBIg8Qg
 @echo:X8PMzMzMzMzMzMzMSIvESIlYCEiJaBBIiXAYV0FWQVdIg+wgQo08AsZAIQCLFWJo
 @echo:AABBi+g7+kyL8Q9H+kQ7xw+DugAAAEG//wAAAEEPtjZJ/8aLBS9oAABMjQ2w/QAA
 @echo:O/CLyg9CxokFG2gAAIsFjf0AADvwD0fGK81BO8+JBX39AABCD74EDkEPR887yHME
 @echo:QogMDoM90WcAAAB1WYvOSP8VmksAAA8fRAAAhcB0QYvOSP8VGEsAAA8fRAAAhcB1
 @echo:L0iNTCRYQIh0JFiL3kj/FRRLAAAPH0QAAA+2MA+2RCRYO9h0C4sVqWcAAOlj////
 @echo:ixWeZwAA/8U77w+CTP///0iLXCRASItsJEhIi3QkUEiDxCBBX0FeX8PMzMzMzMzM
 @echo:SIvESIlYGIlQEEiJSAhVVldBVEFVQVZBV0iD7CCLPSF1AABMjTWW1v//D7YNH3UA
 @echo:AMZAEQCLBTlnAAA7+A9Cx4kFLmcAAEIPtoQxACUBAITAD4WbAAAASGMdEmcAAI1D
 @echo:AYkFCWcAAIH7gAAAAA+NYAIAAEmNtpCgAABCiJwxACUBAEiNNN5IgyYAgz27ZgAA
 @echo:AHV0SP8VhkoAAA8fRAAAhcB0ZIoFp3QAAEiNTCRoiEQkaEj/FQ9KAAAPH0QAAIoN
 @echo:jHQAADgIdRtIjUwkaEj/FVxJAAAPH0QAAIoNcXQAADgIdCQPtkQkaEKInDAAJQEA
 @echo:6xVJjbaQoAAASI00xkiDPgAPhLQBAACD7wF1HEiLDug0/P//SIMmAP8FmvoAALgB
 @echo:AAAA6ZUBAABIix5IjS0fdAAA6cEAAABEi3sQTIvjSGNDEEE7/0yLLQxJAABIi81E
 @echo:D07/TCvggz3vZQAAAEmL1E1jx0wPRS3NSAAASYvF/xWESgAAiUQkYIXAdEVBuAEA
 @echo:AABJi9RIi81Ji8VMi/X/FWRKAACFwHUgTCvlSf/GQbgBAAAASYvOSYvFS40UNP8V
 @echo:REoAAIXAdOOLRCRgRCv16wNFi/dFhfZ1DIXAeDRIi/NIixvrI0U7/nVzRDv/dDdI
 @echo:jXMISIseSIXbD4TMAAAASWPHSAPoQSv/SIXbD4U2////i9dIi83okfv//0iJBkiJ
 @echo:GOkC////SGNDEEiL00gr0ESLx0iLy+g1/P//SIkGSIvYSItICEiFyQ+E4P7//+gF
 @echo:+///SINjCADpy/7//0hjQxCLUxBNY+ZBK9ZJi8xIK8hIA8voNPv//0hjSxBIi9NI
 @echo:K9FFi8ZIi8tMi/jo4Pv//0iJBkEr/ovXSIvYSItICEmJTwhJjQws6AD7//+DfCRg
 @echo:AH0MSIlDCEyJOOlp/v//SYkHTIl7COld/v//M8BIi1wkcEiDxCBBX0FeQV1BXF9e
 @echo:XcPMuQoAAADo8/n//8zMzMzMzMzMzMzMzMzMzMzMzMxIi8RIiVgISIloEEiJcBhI
 @echo:iXggQVdIg+wgiy0xcgAATI09OnIAAIPlEIv6SIvxSYvfhdJ+TooO/89I/8aIC4D5
 @echo:XHQZhf9+NUj/FfJFAAAPH0QAAIXAdCVI/8PrF4X/fhwPvg5I/xUeSAAADx9EAACF
 @echo:wHUJigb/z4gDSP/GSP/Dhf9/soXtdAbGAw1I/8NBK9+DPcVjAAAAiR23cQAAdQqL
 @echo:00mLz+hrJAAASItcJDBIi2wkOEiLdCRASIt8JEhIg8QgQV/pSPz//8zMzMzMzMzM
 @echo:QFNVVldBVUFWQVdIgexAAwAASIsFP2MAAEgzxEiJhCQwAwAATYv4TIvySIvZSDvK
 @echo:D4MHAgAAQb0BAAAAQYvOSIvDK8t0MUGKF0ErzU2Lz4D6AHQYRIrCQYrQRDgAdA1N
 @echo:A81BihFEisKE0nXrhNJ0B0kDxYXJdc8rw0iYSAPYSTveD4O2AQAARYvGSYvXRCvD
 @echo:SIvL6EAoAABIY+iB/QACAAAPjdgBAABIiz1q+AAASIX/D4XtAAAAgf0AAQAAD43N
 @echo:AQAAi9WD/QJ8C4A7XHUGgHsBPHQhhcB+JYoBQSvVSQPNPFx1DUEr1XUFgDk+dAdJ
 @echo:A82F0uvhQYv16YsAAABMi8VIjUwkIEiL0+ioNQAAgf0AAQAAD4NwAQAAxkQsIACA
 @echo:fCQgAHQHgHwsHyR0yUiNTCQg6Ink//9Ii9BIhcB1BDP260aKAEGL9TxedC6EwHQq
 @echo:M/ZIi8pJA81BOsUPhAYBAAA8Ag+E+QAAAA+GAQEAADwFD4f5AAAAQYv1SIvKSP8V
 @echo:fEUAAA8fRAAAhfZIjT2e/f//SI0Fx+v//0gPRfhIiT109wAATIvFSI2MJCABAABI
 @echo:i9Po/zQAAEiNRQHGhCwgAQAACkg9AgIAAA+DzAAAAMaEBCABAAAASI0Fguv//0g7
 @echo:+HRA9gWWbwAACHU3SGMFmWEAAEyNBSZBAABIjZQkIQEAAEgD1UiNjCQgAQAASYsE
 @echo:wP8VIUYAAEiFwHUVSIs99fYAAIvVSIvLSIvH/xUHRgAASAPdSTveD4L//f//M8BI
 @echo:i4wkMAMAAEgzzOgxLAAASIHEQAMAAEFfQV5BXV9eXVvDzEkDzesJD7YBSP/BSAPI
 @echo:igGEwA+EAP///+nW/v//uRAAAADoh/b//8zoyS0AAMy5AgAAAOh29v//zOi4LQAA
 @echo:zMzMzMzMzMxIiVwkCEiJdCQQSIl8JBhBVkiD7CAz9kSL8kiL2Y1+AUiFyXQ0SGNT
 @echo:EEiLy0grykWLxuhN+P//SItLCEiFyXQNi1MQQQPW6LX////rAovHSIsbA/BIhdt1
 @echo:zEiLXCQwhfYPRf5Ii3QkOIvHSIt8JEBIg8QgQV7DzMzMzMzMzMzMzEiJXCQIV0iD
 @echo:7EBIi9lI/xW0QQAADx9EAACD+P90JagQdAZIg8j/63QPuuAMcxX3BSBuAAAAAgAA
 @echo:dQnGBa31AAAB699Ig2QkMABBuAMAAADHRCQoAAAQAEUzyboAAACARIlEJCBIi8tI
 @echo:/xVyQQAADx9EAABIi/hIg/j/dR2NSAPozDAAAEyLBeVzAACNVwVIi8hMi8voTyUA
 @echo:AEiLx0iLXCRQSIPEQF/DzMzMzMzMzMzMzMzMzMzMzMxIg+wog/kBd15mgz0X9QAA
 @echo:AHRUSI0NtrMAAEj/FSdCAAAPH0QAALn1////xgUm9gAAAUj/FY9BAAAPH0QAAA+3
 @echo:FeP0AABIi8hI/xVZQAAADx9EAABIjQ11swAASP8V3kEAAA8fRAAAM8BIg8Qow8zM
 @echo:zMzMzMzMzMzMzMzMzMzMzEBTVVZXQVRBVkFXSIHsUAIAAEiLBd9eAABIM8RIiYQk
 @echo:QAIAAEiDPQRfAAD/SI0dHbMAAEEPt/CL+kiL6XU/ufX///9I/xX+QAAADx9EAABI
 @echo:i8tIiQXXXgAASP8VWEEAAA8fRAAAugEAAABIjQ0P////SP8VmD8AAA8fRAAARTP/
 @echo:ZoX2dFhIi8tI/xU5QQAADx9EAABEOD099QAAdRZIiw2MXgAAD7fWSP8Vej8AAA8f
 @echo:RAAASIvLSP8VA0EAAA8fRAAARDg9D/UAAHQSuQIAAABI/xWhQAAADx9EAADMhf90
 @echo:YUG8AAIAAEE7/IvfQQ9H3EE73A+PiwAAAExj80iNTCRATYvGSIvV6EoxAABIiw0d
 @echo:XgAATI1MJDBEi8NMiXwkIEiNVCRASP8VTD8AAA8fRAAAhcB0WjlcJDB1VEkD7iv7
 @echo:daVmhfZ0Gg+3FVrzAABIiw3bXQAASP8VzD4AAA8fRAAASIuMJEACAABIM8zorygA
 @echo:AEiBxFACAABBX0FeQVxfXl1bw8y5AgAAAOgi8///zA+3FRLzAABIiw2TXQAASP8V
 @echo:hD4AAA8fRAAAuQUAAADo/fL//8zMzMzMzMzMzMzMzMyF0g+ORQEAAEiJXCQISIls
 @echo:JBBIiXQkGFdBVEFVQVZBV0iD7DBEiyVhXQAATI0Frsz//0SLPdvzAABEi/JMi+lF
 @echo:heQPhAcBAABJY99Bi4SYoJAAAIXAD4WHAAAASYuc2DBwAAC59f///0j/FRk/AAAP
 @echo:H0QAAEiDZCQgAEyNDfNwAABIi8hBuAAgAABIi9NI/xUkPgAADx9EAABMYz108wAA
 @echo:TI0FOcz//0SL4IkF3FwAAEuLjPgwcAAAQ8eEuKCQAAAAIAAAS4mM+BiQAABBg/cB
 @echo:SWPHRIk9OvMAAEGLhICgkAAAQTvGSWP/QYvuSYvVD07oSGP1SYuc+BiQAABMi8ZI
 @echo:i8vomy8AAEyNBdLL//9EK/VBKay4oJAAAEiNBB5MA+5JiYT4GJAAAEWF9g+PDv//
 @echo:/0iLXCRgSItsJGhIi3QkcEiDxDBBX0FeQV1BXF/DzLsCAAAAi8vo/SwAAEyLBRZw
 @echo:AACNUwNIi8jogyEAAIvLSP8Vwj8AAA8fRAAAzMzMzMzMzMzMzMzMzMzMzMzMzMzM
 @echo:wgAAzMzMzMzMzMzMzMzMzEiJXCQIV0iD7DBIYx1j8gAASI0FKMv//78AIAAAK7yY
 @echo:oJAAAIX/fn5Ii5zYMHAAALn1////SP8VrD0AAA8fRAAASINkJCAATI0Nhm8AAEiL
 @echo:yESLx0iL00j/Fbo8AAAPH0QAAIPJ/4kFgFsAAIXAD0UNX28AADvPdC27AgAAAIvL
 @echo:6DMsAABMiwVMbwAAjVMDSIvI6LkgAACLy0j/Ffg+AAAPH0QAAMxIi1wkQEiDxDBf
 @echo:w8zMzMzMzMzMzMzMzMzMzEiJXCQgVVZXQVRBVUFWQVdIgexQAQAASIsFuloAAEgz
 @echo:xEiJhCRAAQAAM/ZNi+hEi/5Ii+pMi+FMi/FIiwUv7wAA/xVxPwAASIv4SIXAD4T2
 @echo:AQAAixWnaAAASP/P9sIIdDw5NUnxAAB1ETk1TfEAAHUJSDs9MPAAAHIjgD8KdB5E
 @echo:i8VIjRWXQAAARCvHSIvP6MQfAAD/wEiY6YcBAACJNXVaAAD2wgIPhYYBAABIi8/o
 @echo:YBwAAP/ISJhIK/j2wgF0aEWF/3VASIPI/0j/wEI4NCh190iDwAJIPQYBAAAPh6AB
 @echo:AABNi81MjQU4QAAAugYBAABIjUwkMEj/Ffs9AAAPH0QAAESL+EQPtwWz8AAASI1M
 @echo:JDBIiwVvWQAAQYvX/xWWPgAAixXYZwAA9sIEdG2L1usRQYoOjUIBSf/GgPkKD0XC
 @echo:i9BMO/dy6kSLDQquAABMjQXTPwAARAPKSI1MJCC6DAAAAESJDe+tAABI/xWIPQAA
 @echo:Dx9EAABED7cFQ/AAAEiNTCQgi9BIiwX9WAAA/xUnPgAAixVpZwAATIv3hNJ5RkSL
 @echo:DYetAABMjQWAPwAARSvMSI1MJCBEA8+6DAAAAEj/FTU9AAAPH0QAAEQPtwXw7wAA
 @echo:SI1MJCCL0EiLBapYAAD/FdQ9AACL3UiNFTM/AAAr30iLz0SLw+heHgAASIvNSCvP
 @echo:jVABSGPCSDvBSIsFeFgAAEiLzw9O2kUzwIvT/xWXPQAASGPDSAP4SIvVSIvP6Qj+
 @echo://+4AQAAAOsdQYoGjU4BSf/GPAoPRc6L8Uw79XLrATUErQAAM8BIi4wkQAEAAEgz
 @echo:zOiaIwAASIucJKgBAABIgcRQAQAAQV9BXkFdQVxfXl3DzLkCAAAA6ATu///MzMzM
 @echo:zMzMzEBTVVZXQVZBV0iB7FgBAABIiwUtWAAASDPESImEJEABAACLBURmAAAz7UmL
 @echo:8UmL+EyL+kyL8aiFD4RjAQAATTvBD4NxAQAAqAF0ZoXtdUBIg8j/SP/AQYA8BgB1
 @echo:9kiDwAJIPQYBAAAPh2wBAABNi85MjQUZPgAAugYBAABIjUwkMEj/Fdw7AAAPH0QA
 @echo:AIvoRA+3BZXuAABIjUwkMEiLBVFXAACL1f8VeTwAAIsFu2UAAKgEdFBEiw0IrAAA
 @echo:TI0F0T0AALoMAAAASI1MJCBBjUEBiQXtqwAASP8VhjsAAA8fRAAARA+3BUHuAABI
 @echo:jUwkIIvQSIsF+1YAAP8VJTwAAIsFZ2UAAITAeUZEi89MjQWFPQAARSvPSI1MJCBE
 @echo:Aw12qwAAugwAAABI/xU2OwAADx9EAABED7cF8e0AAEiNTCQgi9BIiwWrVgAA/xXV
 @echo:OwAARIvGSI0VMz0AAEQrx0iLz+hgHAAASGPISIvWSCvXSDvKSIvPjVgBD03YSIsF
 @echo:dFYAAIvTRTPA/xWZOwAASGPDSAP4SDv+cyKLBdBkAADppv7//0iLBUxWAAAr94vW
 @echo:RTPASIvP/xVsOwAASIuMJEABAABIM8zopCEAAEiBxFgBAABBX0FeX15dW8PMuQIA
 @echo:AADoGez//8zMzMzMzMzMzEiLxEiJWAhIiWgQSIlwGEiJeCBBVkiD7CBNi/BIi/JI
 @echo:i+lIi/npqAAAAIsVUGQAAEj/y/bCCHQ+gz3x7AAAAHUSgz307AAAAHUJSDsd1+sA
 @echo:AHIjgDsKdB5Ei8ZIjRU+PAAARCvDSIvL6GsbAAD/wEiYSAPY61ZIi8voFhgAAP/I
 @echo:SJhIK9hIO992HYMlB1YAAAD2wgJ1akyLy0yLx0iL1UmLzuht/f//RIvGSI0V7zsA
 @echo:AEQrw0iLy+gcGwAA/8BImEgD2P8FD6oAAEiL+0iL1kiLy0iLBRfqAAD/FVk6AABI
 @echo:i9hIhcAPhT////9IO/d2KIMloVUAAAD2BYJjAAACdAe4AQAAAOsTTIvOTIvHSIvV
 @echo:SYvO6Pz8//8zwEiLXCQwSItsJDhIi3QkQEiLfCRISIPEIEFew8zMzMzMzMxAU1ZX
 @echo:QVRBVUFWQVdIgeyAAAAASIsFAlUAAEgzxEiJRCR4SYvYSIlcJDhIiVQkUEiJTCRY
 @echo:SIlUJGAz/4k9v+sAAIk9KakAAMcFS6kAAAEAAABEi+eJfCQwSIs1jVQAALn2////
 @echo:SP8VATcAAA8fRAAASDvYi8cPlMCJBXbrAAAPhA0BAABIjVQkNEiLy0j/FRk2AAAP
 @echo:H0QAAIkFtmgAAIP4/3UUSP8V4jUAAA8fRAAAhcAPhSkEAAA5PZdoAAB1Cjl8JDQP
 @echo:hBcEAAA5fCQ0D4W0AAAA9wV3aAAAAAAAgA+FpAAAAEiJfCQoiXwkIEUzyTPSRY1B
 @echo:AkiLy0j/FRU2AAAPH0QAAEiL2EiFwHUfjUgC6CglAABIi8hMiwU+aAAAjVMN6K4Z
 @echo:AADptQMAAEiJfCQgRTPJRTPAQY1RBEiLy0j/FRA2AAAPH0QAAEiJBZzpAABIi8tI
 @echo:/xWaNQAADx9EAABIi1wkOEg5PYHpAAB0GkiLNXjpAABIiTVxUwAAxwUbqAAAAQAA
 @echo:AOsKxwVv6gAAAQAAADk9XeoAAHUIOT1h6gAAdDhIjTXAZwAASIk1PVMAAEiJfCQg
 @echo:TI0NmWcAAEG4ACAAAEiL1kiLy0j/FfY0AAAPH0QAAIkFx6cAAPcFYWEAAAABAAB0
 @echo:PUiL3kSLNWVnAABBg+4BdC2AOyBzHw+2E0iNDXg5AABI/xU5NwAADx9EAABIhcAP
 @echo:hJwCAABI/8NBg8b/ddNJg83/TI0Nv1IAAESLPTynAABBi805PWOnAAAPRQ0QZwAA
 @echo:Qo0EIYXAD45lAgAAOT2e6QAAdSk5PaLpAAB1IUxj8UljxEwr8EwD9ok94mYAAMcF
 @echo:JKcAAAEAAADpYQEAAIXJfxRmxwYNCkiDxgJMi/ZEi+fpSQEAAExj8UmNTv9IA87o
 @echo:sBQAAExj4E0r9EwD9khjTCQwSIPxAUmLBMlIiUQkSEmNNARNi8RJi9ZIi8josSUA
 @echo:AEGB/AAQAAAPjrMAAAC4ACAAAEQ74A+MjQAAAEUD/ESJPXamAABEi+dIi3QkSDk9
 @echo:7OgAAHUIOT3w6AAAdClIiXwkIEyNDTZmAABEi8BIi9ZIi0wkOEj/FZQzAAAPH0QA
 @echo:AIkFZaYAAEG4CgAAAEiNVCRoiw1QpgAASP8VATUAAA8fRAAAuQIAAADo2iIAAEiL
 @echo:yEyNTCRoTIsF62UAALoSAAAA6FkXAADrXjk9cegAAHUIOT116AAAdE5Ei8BFK8Tr
 @echo:IDk9WegAAHUIOT1d6AAAdDZBuAAgAABFK8RBgeAA/P//SIl8JCBMjQ2TZQAASIvW
 @echo:SItMJDhI/xX0MgAADx9EAACJBcWlAABMjQ0KUQAASGNcJDBMi3wkUE2Lx0mL1kmL
 @echo:DNlIi0QkWP8V+zUAAIlEJECFwHRhSf/FQzg8L3X3SYvVRA+3x0mLz0iLBalQAAD/
 @echo:FdM1AABFM8BBjVACSI0NTTcAAEiLBY5QAAD/Fbg1AAA5ParnAAAPhZAAAAA5Parn
 @echo:AAAPhYQAAABIiw2J5gAASIXJdHjrakyNDXtQAABFKzTZRIs99KQAAEUD/kSJPeqk
 @echo:AACDdCQwAemk/f//uQIAAADooiEAAEiLyEyLTCRgTIsFs2QAALoPAAAA6CEWAAAz
 @echo:/zk9OecAAHUjOT095wAAdRtIizUg5gAASIX2dA9Ii85I/xWBMgAADx9EAABIi0wk
 @echo:eEgzzOhXGwAASIHEgAAAAEFfQV5BXUFcX15bw8zMzMzMzMzMSIlcJBhVVldBVEFV
 @echo:QVZBV0iNrCTg+v//SIHsIAYAAEiLBe5PAABIM8RIiYUQBQAAM/ZMY+FIi9pIiVQk
 @echo:UEUzyUSJZCRcRTPAiXQkWESNbgFIiXQkaEGL1UCIdCRAM8lAiHQkQUSL/kSL9kj/
 @echo:FYsxAAAPH0QAAEUzwDPSuQABAABI/xW1MQAADx9EAADoUyEAAI1+CITAdDlFheR0
 @echo:KEGL/EiLE0iLykj/FQ//AAAPH0QAAEiNWwhJK/115UiLXCRQvwgAAABI/xUQMQAA
 @echo:Dx9EAABI/xWEMgAADx9EAAC59f///0j/FXsxAAAPH0QAAEiLyEiNFcTkAABI/xU9
 @echo:MAAADx9EAAAPtwW55AAASI2NsAAAAGYLxzPSQbggAwAAZokF2OUAAOhhIgAASI09
 @echo:VDUAAEGLzUiL10j/FQ8zAAAPH0QAAEiL17kDAAAASP8V+zIAAA8fRAAASIvXuQQA
 @echo:AABI/xXnMgAADx9EAABIi9e5BQAAAEj/FdMyAAAPH0QAAEj/FZ8vAAAPH0QAAEyN
 @echo:BQM1AAC6CAAAAESLyEiNjfADAABI/xW1MgAADx9EAABIjZXwAwAAuQIAAABI/xWN
 @echo:MgAADx9EAABIjQXRNAAARIgtdlwAAEG4AAEAAEiJBXViAABBi9VIjQ0D5AAA6Jwh
 @echo:AABBi82JNUVcAADoOB8AAEiLyEj/FV4yAAAPH0QAAL8AgAAAi8iL10j/FYExAAAP
 @echo:H0QAALkCAAAA6AofAABIi8hI/xUwMgAADx9EAACLyIvXSP8VWDEAAA8fRAAAiXQk
 @echo:SEyNDcjX//9MiWQkYE075Q+OjgQAADPSTI0Fgen//0iJldADAABJi/VIixzzigMs
 @echo:Laj9D4XtAwAASP/D6VsDAABAD77Pg/lYD4+TAAAAD4QcAwAAg/lOf0gPhK8AAACD
 @echo:6T8PhFgDAACD6QMPhNEAAACD6QMPhLwAAACD6QQPhKgAAACD6QMPhI4AAACD+QEP
 @echo:hV0BAACDDVRbAAAC6fgCAACD6U8PhKgAAACD6QEPhN4CAACD6QIPhMcCAACD6QEP
 @echo:hLQCAACD+QMPhSQBAABIjQWb9v//SIkFlEwAAOm4AgAAg/lvD4/bAAAAdGaD6WJ0
 @echo:UYPpA3RAg+kEdDCD6QN0GoPpAXSQg/kBD4XkAAAAgw3bWgAABOl/AgAATIkFZ+IA
 @echo:AMZEJEAB6W4CAACJFctMAADpYwIAAIMNs1oAABDpVwIAALgIAAAACQWjWgAA6UcC
 @echo:AABIjRX/MgAASIvLSP8VpTAAAA8fRAAAhcB1CUiNDeUyAADrI0iNFeQyAABIi8tI
 @echo:/xWCMAAADx9EAAAz0oXAdSdIjQ3IMgAAD7otUFoAAAlI/xXRLgAADx9EAAD/yEiY
 @echo:SAPY6WwBAAAPui0wWgAAB+lhAQAAg+lwD4TDAQAAg+kCD4SsAQAAg+kBD4SZAQAA
 @echo:g+kDD4Tl/v//g/kCD4R+AQAAgHsBOnVZSIPDAjgTD4TkAQAASIvLSP8Vai4AAA8f
 @echo:RAAAi9BAgP9hD4/QAAAAjU+/9sHfdGBAgP9DD4QFAQAAQID/RA+E3gAAAI1HujwB
 @echo:D4a9AAAAjUL/SGPISAPZM9K5AgAAAMZEJEQvQIh8JEWIVCRG6H8cAABMiwWYXwAA
 @echo:TI1MJERIi8i6BgAAAOj+EAAA6Z0AAACKAzPSZokVHuIAAITAdFQPvshI/xWQLwAA
 @echo:Dx9EAACFwHQ6gDs5D74LfwWNQdDrD0j/FYsuAAAPH0QAAIPoVw+3DeThAABI/8Nm
 @echo:weEEZgPIZokN0+EAAIoDhMB1s0SLZCRcM9JI/8vrN0CA/2N0QUCA/2R0Ho1Hmuk7
 @echo:////QIDvRkD2x990BUyL8+tZSIlcJGjrUkyL+//ISGPISAPZM9JMjQVz5v//TI0N
 @echo:nNT//+tjTIuF0AMAAEiNBVzm//9IiQU94AAASYP4ZA+NJQsAAP9EJFhKiZzFsAAA
 @echo:AEn/wEyJhdADAACNQv/rroMNeVgAABjrIMdEJEgBAAAA6xZMiQ3+3wAAxkQkQQHr
 @echo:CA+6LVdYAAAISP/DQIo7QIT/D4WZ/P//Qf/FSWPESP/GSDvwfXBIi1wkUOlp/P//
 @echo:uQEAAADoHhsAAEUzwEiLyEGNUAPopw8AADPJSP8V5i0AAA8fRAAAzLkCAAAAQIh8
 @echo:JESIVCRF6O0aAABMiwUGXgAATI1MJERIi8i6CwAAAOhsDwAAuQIAAABI/xWoLQAA
 @echo:Dx9EAADMgHwkQAB0FIB8JEEAD4VNCgAATIkFSd8AAOsXSIsFQN8AAIB8JEEASQ9F
 @echo:wUiJBTDfAABIY0QkWEiL8EiD+AF8PEiL+kiLnP2wAAAASIXbdCxIi8tI/xX4KwAA
 @echo:Dx9EAABIY9BMjQXVLwAASAPTSIvL6Nbl//9I/8dIO/58xzP2RTvsdRE5NbndAAB1
 @echo:CU2F9g+E1gkAAEiLBd9IAAC5AQAAAMZA/wpIiwXHSAAAxkD/CugOGgAASIvISP8V
 @echo:NC0AAA8fRAAAi8hI/xVOLQAADx9EAACFwHQcSI0Fzun//0iJBW9IAABIjQUQ7f//
 @echo:SIkFaUgAAL/2////TYX2D4TcAAAAQYA+L3UGQTh2AXQMQYA+LXVlQTh2AXVfi89I
 @echo:/xXSKgAADx9EAABIi9hMi8NIjRXYLgAASI0NEeX//+hI8///i89I/xWrKgAADx9E
 @echo:AABIO9h0D0iLy0j/FR8qAAAPH0QAAEyLdCRQOTXX3AAAD4QECQAA6Z0AAABIiXQk
 @echo:MEUzyYl0JChFM8C6AAAAgMdEJCADAAAASYvOSP8VtikAAA8fRAAASIvYSIP4/w+F
 @echo:ev///41IA+gMGQAATIsFJVwAAI1TCEiLyE2LzuiPDQAAjUsDSP8VzSsAAA8fRAAA
 @echo:zDk1YdwAAEyLdCRQdStJY8VB/8VIg8r/SYsMxkj/wkA4NBF190gD0UyNBTkuAADo
 @echo:POT//+lS////SI0FkNH//0g5BUHdAAAPhF8BAACLBdFHAABIjQ1G3QAAQbj/AAAA
 @echo:QTvAjVABQQ9D0EG4AAEAAOjJGgAASI0F1AkAAIv+SIkF29sAAEyNNeS2//+L3jk1
 @echo:aEcAAHUki8tI/xUxKwAADx9EAACFwHQSi8tI/xWvKgAADx9EAACFwHVSi/NFM+RG
 @echo:OKQ2ACUBAHRBRTPAiFwkQEGNVCQBSI1MJEDovd7//0yNJYq2//+6AQAAAEoPvowm
 @echo:ACUBAEmLjMyQoAAA6Bfm//8D+EyNNWa2//8z9v/DgfsAAQAAD4J0////iwVI2wAA
 @echo:RItkJFxMi3QkUDv4dGi7DwAAAEiNleADAABEi8OLz0SNS/tI/xWuKQAADx9EAACL
 @echo:DRPbAABEjUv7RIvDSI2V0AMAAEj/FY4pAAAPH0QAAI1L8+hxFwAASIvITI2N0AMA
 @echo:AEyNheADAACNU/no8AsAAIsF0toAAIP4AXUtOTVbRgAAdCVIjQWWBwAA6xVIiwWt
 @echo:2gAASI0NBtP//0iFwEgPRMFIiQWY2gAASIt8JGhIhf8PhCQBAACDDRNUAAABgD8v
 @echo:dQZAOHcBdAuAPy11FUA4dwF1DzPJ6O4WAABIi9jptwAAAEiNFWMsAABIi89I/xUF
 @echo:KQAADx9EAABIi9hIhcAPhZUAAACNSALovBYAAEyLBdVZAACNUwlIi8hMi8/oPwsA
 @echo:AI1LAkj/FX0pAAAPH0QAAMxIjRXYKwAASI2NAAQAAEj/FZIpAAAPH0QAAEg9BQEA
 @echo:AA+DLwYAAEiNjQAEAABAiLQFAAQAAOgN5f//SIv4SIP4/3QlSIsN1UQAAEiNlQAE
 @echo:AABMi8DoAvD//0iLz0j/FewmAAAPH0QAAEyLw0iNjQAEAAC6BQEAAEj/FVEpAAAP
 @echo:H0QAAEiFwA+FdP///zPJ6AQWAABIO9h0P0iLy0j/FUUoAAAPH0QAAOsuRTvsdSmD
 @echo:JepSAAD8ufb///9I/xUGJwAADx9EAABIiw1SRAAAM9JMi8DohO///4t0JEhBjUUB
 @echo:M9tEO+B/LYX2dSlFO+x9Kw+u6EljxUmLDMZIhcl0HOsLPD90DzwqdAtI/8GKAYTA
 @echo:de/rB4MNhVIAAAFNhf8PhKMCAABBOB8PhJoCAAAz0jPJSP8VmCYAAA8fRAAAM/aL
 @echo:+IXAD4Q/AgAAi89I/xVOJwAADx9EAABIi9hIhcB1Ko1OAugxFQAATIsFSlgAAI1W
 @echo:AkiLyOi3CQAAjU4CSP8V9ScAAA8fRAAAzEiL04vPSP8VOyYAAA8fRAAAhcAPhOYB
 @echo:AABEi3QkSLo7AAAASYvPSP8V6icAAA8fRAAASIlEJGBIi/hIhcB0A0CIMEE4Nw+E
 @echo:UQEAAEQPtwWE2gAASI0NPSoAAEiLBT5DAAC6AgAAAP8VYygAAEmLz0j/FSkmAAAP
 @echo:H0QAAEQPtwVU2gAASYvPi9BIiwUQQwAA/xU6KAAARA+3BTraAABIjQ33KQAASIsF
 @echo:9EIAALoDAAAA/xUZKAAASIvLSP8VjyUAAA8fRAAAhcAPhPAAAABJi89I/xV4JQAA
 @echo:Dx9EAACFwHUkjUgC6CcUAABMiwVAVwAASIvITYvPugQAAADoqAgAAOmYAAAASItM
 @echo:JFBBi/RJY8VBK/VEi85EiXQkIEyNPMFNi8dIjY0ABAAA6PLR//+FwHhpRItkJEhI
 @echo:jY0ABAAA6H3i//9Mi/BIg/j/dCVIiw1FQgAASI2VAAQAAEyLwOhy7f//SYvOSP8V
 @echo:XCQAAA8fRAAARIvORIlkJCBNi8dIjY0ABAAA6JjR//+FwHmrSIt8JGBEi2QkXESL
 @echo:dCRIM/ZMjX8BSIX/D4V1/v//SIvLSP8V5CUAAA8fRAAA6fkAAABIi8tI/xXQJQAA
 @echo:Dx9EAAC5AgAAAOg5EwAATIsFUlYAAEiLyEyLy7oEAAAA6LoHAAC5AgAAAEj/FfYl
 @echo:AAAPH0QAAMxIi8tI/xWOJQAADx9EAAC5AgAAAOj3EgAATIsFEFYAAEiLyLoRAAAA
 @echo:6HsHAAC5AgAAAEj/FbclAAAPH0QAAMyF9g+E1QAAAEU75Q+OzAAAAEiLTCRQRSvl
 @echo:SWPFSI08wes6SI2NAAQAAOhT4f//SIvYSIP4/3QlSIsNG0EAAEiNlQAEAABMi8Do
 @echo:SOz//0iLy0j/FTIjAAAPH0QAAEWLzIl0JCBMi8dIjY0ABAAA6G/Q//+FwHmsM/ZI
 @echo:iwXqQAAA/xUMJgAAQDg149YAAHQeuQIAAADoORIAAEyLBVJVAABIi8i6FgAAAOi9
 @echo:BgAAiwU/QQAASIuNEAUAAEgzzOgYDAAASIucJHAGAABIgcQgBgAAQV9BXkFdQVxf
 @echo:Xl3DzElj9Ug7dCRgfY9Ii0QkUEmDzP9MjTTwSYsOSI1UJHBI/xVmIgAADx9EAABM
 @echo:i+hJO8R1JrkCAAAA6LcRAABNiw5Ii8hMiwXKVAAAugQAAADoOAYAAOkLAQAASYs+
 @echo:TYv8Sf/HQjgcP3X3SYvcM9JI/8M4FB91+IXbeCVMY+NMA+dBgDwkXHUQi9NIi8/o
 @echo:fAcAADPShcB0Fkn/zIPrAXnhSIvKSIXJdA4rz//B6xtIY8tIA8/r7UmD/wJyC4B/
 @echo:ATq5AgAAAHQCi8pJg8z/SI1FnE2LxEn/wEI4FAB190hj2UiNQwFJA8BIPQQBAAAP
 @echo:h4oAAABIjU2cSf/ASAPLSI1VnOg6EwAATIvDSI1NnEiL1+grEwAASI1NnOiI3///
 @echo:SIvYSTvEdCJIiw1RPwAASI1VnEyLwOiB6v//SIvLSP8VayEAAA8fRAAASI1UJHBJ
 @echo:i81I/xUHIQAADx9EAAAz24XAD4X1/v//SP/GSYPGCEg7dCRgD4yh/v//6R7+//+5
 @echo:AgAAAOgH1f//zLkVAAAA6PzU///MuRMAAADo8dT//8y5AQAAAOjm1P//zLkMAAAA
 @echo:6NvU///M6B0MAADMzMzMzMzMzMxIiVwkCEiJdCQYV0iD7CDGRCQ5AEiL+Uhj8oXS
 @echo:flMz2w+2DDtI/xXxIgAADx9EAACFwHQfigQ7SI1MJDiIRCQ4SP8V5SEAAA8fRAAA
 @echo:igiIDDvrFooMO0j/Fc8gAAAPH0QAAIXAdANI/8NI/8NIO958r0iLXCQwSIvHSIt0
 @echo:JEBIg8QgX8PMzMzMzMzMzEiJXCQISIlsJBBIiXQkGFdBVkFXSIPsIIsFlkwAAEiL
 @echo:+v/ISIvZTGPATIvxSSv4SDv5dmmL6UyNPYNMAACL00mLzivVSYv36HQFAABMYw1h
 @echo:TAAAhcB1JUGL0UWFyX4ZTIvDTSvHig5BigQwSP/GOsh1Bv/KhdJ/7YXSdD1IjUMB
 @echo:SDvHcxhBD7YMGUiNBc/TAAAPtgQBSAPYSDvfcqAzwEiLXCRASItsJEhIi3QkUEiD
 @echo:xCBBX0FeX8PMSIvD6+HMzMzMzMyDPZXUAAAASI1BAXUcgz2U1AAAAHUTSP/ISDsF
 @echo:dNMAAHIPgDgKde/rCEj/yIA4CnX4K8iLwcPMzMzMzMzMzMzMzMzMzMzMzMzMzMzM
 @echo:SGMFpT0AAEyNBTIdAABJiwTASP8lPyIAAMzMzMzMzMxIi8RIiVgISIloEEiJcBhI
 @echo:iXggQVRBVkFXSIPsIEiL8kyL+osViz0AAEiL2UyL8Y1C/4P4/XcQRI1C/0kr8Eg7
 @echo:8Q+CvgAAAEg7zg+DtQAAAEyNJams//8PtgNCD7a8IAAlAQBAhP90b4vTSYvOQSvW
 @echo:6BsEAACFwHVYSYu8/JCgAABIhf90PEiNawFMY0cQSYvHSCvFSTvAfDBIi9dIi81J
 @echo:K9BI/xXPHwAADx9EAACFwHUVSGNHEEiLfwhIA+hIhf91yEiLw+tAeAhIiz9Ihf91
 @echo:uYsV3TwAAEiNQwFIO8ZzJYP6/3UFSIvY6xKLwg+2DBhCD7aEITAmAQBIA9hIO94P
 @echo:glL///8zwEiLXCRASItsJEhIi3QkUEiLfCRYSIPEIEFfQV5BXMPMzMzMzMzMzMzM
 @echo:SIlcJBBVVldBVEFVQVZBV0iD7CBEiw1pPAAASIvySIvZSIlMJHBBjUH/g/j9dxBF
 @echo:jUH/SSvwSDvxD4JKAQAASDvOD4NBAQAATI01gav//w+2A0IPtrwwACUBAECE/w+E
 @echo:7wAAAIvTK9Ho8wIAAIXAD4XXAAAASYu8/pCgAABIhf8PhJ8AAACNUAFIi8vozwIA
 @echo:AIvQTI1rAUxjfxBMi/eDZCRgAE0r902L5YvqRYX/dFlBD7YGQTgEJHUjhe11G0GK
 @echo:DCRI/xV3HQAADx9EAACFwHQHvQEAAADrJDPt6yCF7XVJRI1FAUmL1kmLzEj/FXYe
 @echo:AAAPH0QAAIvIhcB1NEn/xEn/xkGD7wF1p4vVM8mFyXUmSGNHEEiLfwhMA+hIhf8P
 @echo:hXL///9Ii8PrYUEPtgwkK8iLVCRg69Z4DEiLP0iF/w+FUv///0yNNYSq//9Eiw0x
 @echo:OwAASI1DAUg7xnMtQYP5/3UFSIvY6xNBi8EPtgwYQg+2hDEwJgEASAPYSDvecwpI
 @echo:i0wkcOnG/v//M8BIi1wkaEiDxCBBX0FeQV1BXF9eXcPMzMzMzMzMzEyL0kiLwUWF
 @echo:wHQiQf/ITYvKQYA6AHQRQYoSOBB0D0n/wUGKEYTSdfJI/8Dr2SvBw8zMzMzMzMzM
 @echo:SIvEiVAQTIlAGEyJSCBVU0iNqIjQ//+4aDAAAOjfDQAASCvgSIsFHToAAEgzxEiJ
 @echo:hVAvAABIjYWQLwAASIvZSIlEJEhEi8JIjUQkSEUzyUiJRCQwM9JIjUQkUMdEJCgA
 @echo:EAAAuQAIAABIiUQkIEj/FfQbAAAPH0QAAIlEJECFwA+EtAAAAEyNTCRQiUQkIEyN
 @echo:RCRAugAgAABIjY1QDwAASP8VWh4AAA8fRAAAhcB4dYtEJEBMjY1QDwAATI1EJECJ
 @echo:RCQguv8PAABIjUwkUEj/FRweAAAPH0QAAIXAeDKLRCRASD0AEAAAD4OHAAAATI1E
 @echo:JFDGRARQAEiNFfofAABIi8tI/xWwHQAADx9EAADrS0j/FaIaAAAPH0QAAEiNDd4f
 @echo:AADrKEj/FY0aAAAPH0QAAEiNDfEfAADrE0j/FXgaAAAPH0QAAEiNDQwgAACL0Ej/
 @echo:FaMdAAAPH0QAAEiLjVAvAABIM8zoBwQAAEiBxGgwAABbXcPM6M8FAADMzMzMzMzM
 @echo:SIlcJAhIiWwkEEiJdCQYV0iD7CBIY9pIi+mL80iL+4XSdByKTC//SP8VshoAAA8f
 @echo:RAAAhcB0CP/OSIPvAXXkK96B4wEAAIB9B//Lg8v+/8NIi2wkOIvDSItcJDBIi3Qk
 @echo:QEiDxCBfw8zMzMzMzMzMzEiD7DiLBXofAABMiw2HGQAATIsFcB8AAIlEJChIiVQk
 @echo:IEiL0UiNDdWn//9I/xV2GQAADx9EAABIg8Q4w8zMzMzMzMzMzMzMzMzMzMzMzMzM
 @echo:SIPsKLhNWgAAZjkFoKf//3QEM8DrU0hjDc+n//9IjQWMp///SAPIgTlQRQAAdeO4
 @echo:CwEAAGY5QRh0HrgLAgAAZjlBGHXNM8CDuYQAAAAOdhk5gfgAAADrDjPAg3l0DnYJ
 @echo:OYHoAAAAD5XAuQEAAACJBRw4AADoXwYAAIvI/xV3GwAASIsNSBsAAEiDyP9IiQVl
 @echo:zgAASIkFZs4AAIsFUDcAAIkBSIsNHxsAAIsFYT0AAIkB6HoGAACDPUM3AAAAdQ1I
 @echo:jQ1qBgAA/xUUGwAAM8BIg8Qow8zMzMzMzMzMzMzMzMxIg+w4iwUuPQAATI0FlzcA
 @echo:AESLDRw9AABIjRWBNwAAiQWPNwAASI0NbDcAAEiNBYE3AABIiUQkIP8V4hoAAIkF
 @echo:WDcAAEiDxDjDzMzMzMzMzEiJXCQISIl0JBBIiXwkGEFXSIPsMGVIiwQlMAAAAEiL
 @echo:WAgz9jPA8EgPsR2pzQAAdBtIO8N1CbsBAAAAi/PrErnoAwAA/xVuGQAA69i7AQAA
 @echo:AIsFic0AADvDdQy5HwAAAOiOBQAA62WLBXPNAACFwHVViR1pzQAATI09chsAAEiN
 @echo:PVMbAABIiXwkKIlEJCBJO/9zJYXAdSVIgz8AdBBIiwdIiw0RGwAA/9GJRCQgSIPH
 @echo:CEiJfCQo69aFwHQQuP8AAADp4gAAAIkdeDYAAIsFDs0AADvDdR1IjRXzGgAASI0N
 @echo:3BoAAOjlBgAAxwXtzAAAAgAAAIX2dQkzwEiHBdjMAABIgz3gzAAAAHQqSI0N18wA
 @echo:AOhKBQAAhcB0GkUzwEGNUAIzyUiLBb7MAABMiw2HGgAAQf/RTIsFHTYAAEiLFQ42
 @echo:AACLDQA2AADod+X//4kF7TUAAIM9BjYAAAB1CIvI/xV0GQAAgz3ZNQAAAHUM/xVF
 @echo:GQAAiwXHNQAA6y2JBb81AACDPdg1AAAAdQmLyP8VLhkAAMyDPao1AAAAdQz/FRYZ
 @echo:AACLBZg1AABIi1wkQEiLdCRISIt8JFBIg8QwQV/DzMzMzMzMzMzMzMzMzMzMzMzM
 @echo:SIPsKOgbBQAASIPEKOke/v//zMzMzMzM/yX6FwAAzMzMzMzMzMxmZg8fhAAAAAAA
 @echo:SDsN0TQAAHUQSMHBEGb3wf//dQHDSMHJEOlCAAAAzMzMzMzMQFNIg+wgSIvZM8n/
 @echo:FQMWAABIi8v/FQIWAAD/FQQXAABIi8i6CQQAwEiDxCBbSP8l+BYAAMzMzMzMzMzM
 @echo:SIlMJAhIgeyIAAAASI0NnTUAAP8V/xgAAEiLBYg2AABIiUQkSEUzwEiNVCRQSItM
 @echo:JEj/FQAZAABIiUQkQEiDfCRAAHRCSMdEJDgAAAAASI1EJFhIiUQkMEiNRCRgSIlE
 @echo:JChIjQVHNQAASIlEJCBMi0wkQEyLRCRISItUJFAzyf8VuxgAAOsjSIsFujUAAEiL
 @echo:AEiJBRA2AABIiwWpNQAASIPACEiJBZ41AABIiwX3NQAASIkFaDQAAEiLhCSQAAAA
 @echo:SIkFaTUAAMcFPzQAAAkEAMDHBTk0AAABAAAAxwVDNAAAAwAAALgIAAAASGvAAEiN
 @echo:DTs0AABIxwQBAgAAALgIAAAASGvAAUiNDSM0AABIixVkMwAASIkUAbgIAAAASGvA
 @echo:AkiNDQg0AABIixVRMwAASIkUAbgIAAAASGvAAEiLDTUzAABIiUwEaLgIAAAASGvA
 @echo:AUiLDSgzAABIiUwEaEiNDbwSAADoW/7//0iBxIgAAADDzMzMzMzMzEiD7HhIjQ0t
 @echo:NAAA/xWPFwAASIsFGDUAAEiJRCRIRTPASI1UJFBIi0wkSP8VkBcAAEiJRCRASIN8
 @echo:JEAAdEJIx0QkOAAAAABIjUQkWEiJRCQwSI1EJGBIiUQkKEiNBdczAABIiUQkIEyL
 @echo:TCRATItEJEhIi1QkUDPJ/xVLFwAA6yNIiwVKNAAASIsASIkFoDQAAEiLBTk0AABI
 @echo:g8AISIkFLjQAAEiLBYc0AABIiQX4MgAAxwXeMgAACQQAwMcF2DIAAAEAAADHBeIy
 @echo:AAABAAAAuAgAAABIa8AASI0N2jIAAEjHBAEIAAAASI0NuxEAAOha/f//SIPEeMPM
 @echo:zMzMzMzMzMzMzMzMzMzMzEiD7ChIiwGBOGNzbeB1I4N4GAR1HYtIII2B4Pps5oP4
 @echo:AnYIgfkAQJkBdQf/FX8VAADMM8BIg8Qow8zMzMzMzMxIg+woSI0Ntf////8VBxMA
 @echo:ADPASIPEKMPMzMzMzMz/JawVAADMzMzMzMzMzEiD7Bgz0kiNQf9Ig/j9dzy4TVoA
 @echo:AGY5AXUqOVE8fCWBeTwAAAAQcxxIY0E8SAPBSIkEJIE4UEUAAEgPRcJIi9BIiQQk
 @echo:6wYz0kiJFCRIi8JIg8QYw8zMzMzMzMzMQFNIg+wgi9kzyf8VKBMAAEiFwHQoSIvI
 @echo:6If///9IhcB0G7kCAAAAZjlIXHUEi8HrDmaDeFwDuAEAAAB0AovDSIPEIFvDzMzM
 @echo:zMzM/yXvFAAAzMzMzMzMzDPAw8zMzMzMzMzMzMzMzMxMY0E8RTPJTAPBTIvSQQ+3
 @echo:QBRFD7dYBkiDwBhJA8BFhdt0HotQDEw70nIKi0gIA8pMO9FyDkH/wUiDwChFO8ty
 @echo:4jPAw8zMzMzMzMzMzMzMzEiJXCQIV0iD7CBIi9lIjT0MoP//SIvP6EQAAACFwHQi
 @echo:SCvfSIvTSIvP6IL///9IhcB0D4tAJMHoH/fQg+AB6wIzwEiLXCQwSIPEIF/DzMzM
 @echo:zMzMzMzMzMzMzMzMzMzMzLhNWgAAZjkBdSBIY0E8SAPBgThQRQAAdRG5CwIAAGY5
 @echo:SBh1BrgBAAAAwzPAw8zMzMzMzMxIiVwkIFVIi+xIg+wgSINlGABIuzKi3y2ZKwAA
 @echo:SIsFwS8AAEg7ww+FkwAAAEiNTRj/FaYSAABIi0UYSIlFEP8VKBIAAIvASDFFEP8V
 @echo:JBIAAIvASDFFEP8VeBIAAIvASMHgGEgxRRD/FWgSAACLwEiNTRBIM0UQSDPBSI1N
 @echo:IEiJRRD/Ff0RAACLRSBIuf///////wAASMHgIEgzRSBIM0UQSCPBSIvISDvDdQ1I
 @echo:uDOi3y2ZKwAASIvISIkNJS8AAEiLXCRISPfQSIkFHi8AAEiDxCBdw8zMzMzMzP8l
 @echo:1BIAAMzMzMzMzMzMzMzMzMIAAMzMzMzMzMzMzMzMzMzMzMzMzMzMzEBTSIPsIIvZ
 @echo:6PcAAABIjRRbSMHiBEgDwkiDxCBbw8zMzMzMzEiNBV3eAADpAAAAAEiJTCQISIlU
 @echo:JBBMiUQkGEyJTCQgSIPsaGYPf0QkIGYPf0wkMGYPf1QkQGYPf1wkUEiL0EiNDbIc
 @echo:AADoGfb//2YPb0QkIGYPb0wkMGYPb1QkQGYPb1wkUEiLTCRwSItUJHhMi4QkgAAA
 @echo:AEyLjCSIAAAASIPEaOsA/+DMzMzMzMzMSIPsKIsNRjQAAIP5AXUEisHrNoP5AnQv
 @echo:SI1UJDDGRCQwAEiNDb8NAADoOgAAAIXAeBWKRCQwisj22RvSg8ICiRULNAAA6wIy
 @echo:wEiDxCjDzMzMzMzM/yVWEgAAzMzMzMzMzMzMzMzMzMz/JcIOAADMzMzMzMxIg+wo
 @echo:TYtBOEiLykmL0egRAAAAuAEAAABIg8Qow8zMzMzMzMxAU0WLGEiL2kGD4/hMi8lB
 @echo:9gAETIvRdBNBi0AITWNQBPfYTAPRSGPITCPRSWPDSosUEEiLQxCLSAhIi0MI9kQB
 @echo:Aw90Cw+2RAEDg+DwTAPITDPKSYvJW+ll+P//zMzMzMzMzMzMSIvESIlYCEiJaBBI
 @echo:iXAYSIl4IEFWSIPsIE2LUThIi/JNi/BIi+lJi9FIi85Ji/lBixpIweMESQPaTI1D
 @echo:BOha////i0UEJGb22LgBAAAAG9L32gPQhVMEdBJMi89Ni8ZIi9ZIi83/FdkPAABI
 @echo:i1wkMEiLbCQ4SIt0JEBIi3wkSEiDxCBBXsPMzMzMzMzMzMzMzMz/JSwQAADMzMzM
 @echo:zMz/JTAQAADMzMzMzMz/JRQRAADMzMzMzMzMzMzMzMzMzMzMzMxmZg8fhAAAAAAA
 @echo:/+DMzMzMzMzMzMzMzMzMzMzMzMzMzGZmDx+EAAAAAABIg+wQTIkUJEyJXCQITTPb
 @echo:TI1UJBhMK9BND0LTZUyLHCUQAAAATTvTcxVmQYHiAPBNjZsA8P//RYQbTTvTcvFM
 @echo:ixQkTItcJAhIg8QQw8zMzMzMzMzMzMzMzMzMzMzMzMxAVUiD7CBIi+pIiwEzyYE4
 @echo:BQAAwA+UwYvBSIPEIF3DzMzMzMzMzEBVSIPsMEiL6kiLATPJgTgGAADAD5TBi8FI
 @echo:g8QwXcPMzMzMzMzMQFVIg+wgSIvqSIsBSIvRiwjo7Pn//5BIg8QgXcPMAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:8JAAQAEAAACQkQBAAQAAAFAAUgAAAAAAIHYAQAEAAAAwVABAAQAAAABTAEABAAAA
 @echo:4OQAQAEAAADgBAFAAQAAABgBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAABYkABAAQAAAAAAAAAAAAAAAAAAAAAAAAAwdQBAAQAAADh1AEABAAAA
 @echo:eHUAQAEAAAAaAAAAAAAAAAB1AQAAAAAAAAAAAAAAAADgdQBAAQAAAAMAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAABYjQAAAAAAAAAAAAAAAAAAEogAAAAAAACqhwAAAAAAAAAAAAAAAAAA
 @echo:wocAAAAAAADghwAAAAAAAAAAAAAAAAAAjI0AAAAAAAAAAAAAAAAAAHSNAAAAAAAA
 @echo:AAAAAAAAAADciQAAAAAAAMCJAAAAAAAAxogAAAAAAAAAAAAAAAAAADiIAAAAAAAA
 @echo:gocAAAAAAABaiQAAAAAAANaIAAAAAAAAkocAAAAAAACehwAAAAAAAOyIAAAAAAAA
 @echo:cIcAAAAAAAAAAAAAAAAAAEaJAAAAAAAAAAAAAAAAAAD6iAAAAAAAAAAAAAAAAAAA
 @echo:CIkAAAAAAAAAAAAAAAAAADCJAAAAAAAAAAAAAAAAAAAiigAAAAAAAAAAAAAAAAAA
 @echo:HokAAAAAAAB2iQAAAAAAAIiJAAAAAAAAAAAAAAAAAACoiQAAAAAAAJyIAAAAAAAA
 @echo:AAAAAAAAAAAoiAAAAAAAAISIAAAAAAAArogAAAAAAAAAAAAAAAAAAPqJAAAAAAAA
 @echo:DooAAAAAAABoiQAAAAAAAFCKAAAAAAAAZooAAAAAAAAAAAAAAAAAADaKAAAAAAAA
 @echo:AAAAAAAAAAB4iAAAAAAAAAAAAAAAAAAAXIgAAAAAAABEiAAAAAAAAPqHAAAAAAAA
 @echo:AAAAAAAAAAC4iQAAAAAAAAAAAAAAAAAAlooAAAAAAAB8igAAAAAAAAAAAAAAAAAA
 @echo:6oQAAAAAAADAhAAAAAAAAOCEAAAAAAAA9oQAAAAAAAB8hQAAAAAAAIaFAAAAAAAA
 @echo:kIUAAAAAAAAChQAAAAAAAJqFAAAAAAAAooUAAAAAAABshQAAAAAAAGCFAAAAAAAA
 @echo:VIUAAAAAAACqhQAAAAAAABCFAAAAAAAAtIUAAAAAAAC+hQAAAAAAABSOAAAAAAAA
 @echo:SoUAAAAAAAAejgAAAAAAAEKFAAAAAAAAOIUAAAAAAADWhgAAAAAAAL6GAAAAAAAA
 @echo:tIYAAAAAAACohgAAAAAAAJSGAAAAAAAAioYAAAAAAACChgAAAAAAAHCGAAAAAAAA
 @echo:YIYAAAAAAADYhAAAAAAAAC6FAAAAAAAAUoYAAAAAAABEhgAAAAAAADiGAAAAAAAA
 @echo:LoYAAAAAAAAkhQAAAAAAACCGAAAAAAAAFIYAAAAAAAAGhgAAAAAAAPyFAAAAAAAA
 @echo:9IUAAAAAAADqhQAAAAAAAN6FAAAAAAAA1IUAAAAAAADKhQAAAAAAAEqNAAAAAAAA
 @echo:GoUAAAAAAAAojgAAAAAAAAAAAAAAAAAAJIcAAAAAAAAQhwAAAAAAAASHAAAAAAAA
 @echo:6oYAAAAAAAA4hwAAAAAAAFKHAAAAAAAAAAAAAAAAAABgYQBAAQAAAPBjAEABAAAA
 @echo:AAAAAAAAAAAwWQBAAQAAAAAAAAAAAAAAAAAAAAAAAABQWABAAQAAAKBeAEABAAAA
 @echo:AAAAAAAAAACgGAAAYBoAAFAdAAAwLAAAAC0AAOAwAABgMQAAIDMAALA0AADANAAA
 @echo:gDUAAAA6AADQUQAA4FIAAABTAAAwVAAAAFgAAFBYAAAwWQAAUFsAAOBbAABgXgAA
 @echo:oF4AAIBfAABgYQAAkGIAAJhxAAB4cwAAmHMAAAAAAABleHQtbXMtd2luLW50dXNl
 @echo:ci1jaGFydHJhbnNsYXRpb24tbDEtMS0wLmRsbAAAAABlAHgAdAAtAG0AcwAtAHcA
 @echo:aQBuAC0AbgB0AHUAcwBlAHIALQBjAGgAYQByAHQAcgBhAG4AcwBsAGEAdABpAG8A
 @echo:bgAtAGwAMQAtADEALQAwAAAAAAAuXFsqAAAAAAAAAAD/fwAA/38AAAIAAAAhAAAA
 @echo:AQAAAP9/AAAqLioAXAAAAAoAAAAlczoAJXU6ACVsdToAAAAAAAAAAAgJCw0KDBoA
 @echo:DQoAAAAAAAAuAE8AQwBQAAAAAAAAAAAALgAlAGQAAABGSU5EU1RSAE9GRkxJTkUA
 @echo:T0ZGAAAAAAAgCQAAcgAAACAgAAA6DQoAJXMAAAAAAABGYWlsdXJlIHRvIGNvbnZl
 @echo:cnQgVW5pY29kZSB0byBPZW06ICVkCgAARmFpbHVyZSB0byBjb252ZXJ0IE11bHRp
 @echo:Qnl0ZSB0byBVbmljb2RlOiAlZAoAAAAARm9ybWF0TWVzc2FnZSBmYWlsZWQ6ICVk
 @echo:CgAAAAAAAAAAAAAAAAAAAP////////////////////8AAAAAcVktDQAAAAACAAAA
 @echo:JAAAAPR3AAD0YQAAAAAAAHFZLQ0AAAAADQAAAIwCAAAYeAAAGGIAAAAAAABxWS0N
 @echo:AAAAABAAAAAkAAAApHoAAKRkAABSU0RTTn6UAs8iFD9Jl6DcagFlXQEAAABmaW5k
 @echo:c3RyLnBkYgBHQ1RMABAAAOBTAAAudGV4dCRtbgAAAADgYwAAgAAAAC50ZXh0JG1u
 @echo:JDAwAGBkAAB6AAAALnRleHQkeAAAcAAAWAEAAC5yZGF0YSRicmMAAFhxAADYAwAA
 @echo:LmlkYXRhJDUAAAAAMHUAABAAAAAuMDBjZmcAAEB1AAAIAAAALkNSVCRYQ0EAAAAA
 @echo:SHUAAAgAAAAuQ1JUJFhDQUEAAABQdQAACAAAAC5DUlQkWENaAAAAAFh1AAAIAAAA
 @echo:LkNSVCRYSUEAAAAAYHUAAAgAAAAuQ1JUJFhJQUEAAABodQAACAAAAC5DUlQkWElZ
 @echo:AAAAAHB1AAAIAAAALkNSVCRYSVoAAAAAeHUAAGgAAAAuZ2ZpZHMAAOB1AAAQAAAA
 @echo:LmdpYXRzAADwdQAABAIAAC5yZGF0YQAA9HcAANQCAAAucmRhdGEkenp6ZGJnAAAA
 @echo:yHoAAMwDAAAueGRhdGEAAJR+AAAgAAAALmRpZGF0JDIAAAAAtH4AACQAAAAuZGlk
 @echo:YXQkMwAAAADYfgAAEAAAAC5kaWRhdCQ0AAAAAOh+AAAQAAAALmRpZGF0JDYAAAAA
 @echo:+H4AABAAAAAuZGlkYXQkNwAAAAAIfwAAzAEAAC5pZGF0YSQyAAAAANSAAAAUAAAA
 @echo:LmlkYXRhJDMAAAAA6IAAANgDAAAuaWRhdGEkNAAAAADAhAAAcgkAAC5pZGF0YSQ2
 @echo:AAAAAACQAABAAAAALmRhdGEkYnJjAAAAQJAAAIAAAAAuZGF0YQAAAMCQAAAwlwAA
 @echo:LmJzcwAAAAAAMAEA6AIAAC5wZGF0YQAAAEABABAAAAAuZGlkYXQkNQAAAAAAUAEA
 @echo:8AAAAC5yc3JjJDAxAAAAAPBQAQAYBwAALnJzcmMkMDIAAAAAIAAAAE5+lALPIhQ/
 @echo:SZeg3GoBZV2Dk7Ow1XzTHlWKluFxWS0NAQ8GAA9kBwAPNAYADzILcAEUBgAUZAkA
 @echo:FDQGABQyEHABBQIABTQBABk3DQAmdFMAJmRSACY0UQAmAUoAGPAW4BTQEsAQUAAA
 @echo:nGIAAEACAAABGQoAGXQLABlkCgAZVAkAGTQIABlSFfAZJgkAGDQuABgBJgAM8Arg
 @echo:CHAHYAZQAACcYgAAIAEAABksCwAeZDUAHjQ0AB4BLAAS8BDgDtAMcAtQAACcYgAA
 @echo:UAEAAAkSBwASYg7wDOAKwAhwB2AGMAAAaFsAAAEAAADuHQAAIB4AAHBkAAAgHgAA
 @echo:AQYCAAYyAlABHQwAHXQLAB1kCgAdVAkAHTQIAB0yGfAX4BXAGTALAB80yQAfAcAA
 @echo:EPAO4AzQCsAIcAdgBlAAAJxiAADwBQAAAQYCAAYyAjABBAEABEIAAAEKAgAKMgYw
 @echo:ARkKABl0CQAZZAgAGVQHABk0BgAZMhXgARgKABhkCgAYVAkAGDQIABgyFPAS4BBw
 @echo:AR0KAB00DgAdMhnwF+AV0BPAEXAQYA9QARkKABl0CQAZZAgAGVQHABk0BgAZMhXw
 @echo:GSQJABIBaAAL8AngB9AFcARgA1ACMAAAnGIAADADAAABFQgAFXQIABVkBwAVNAYA
 @echo:FTIR4AEKBAAKNAoACnIGcBkkCQASAUoAC/AJ4AfABXAEYANQAjAAAJxiAABAAgAA
 @echo:ASQMACRkDgAkVA0AJDQMACRSIPAe4BzQGsAYcAEKBAAKNAgAClIGcBkpCwAXNDUA
 @echo:FwEqABDwDuAM0ArACHAHYAZQAACcYgAAQAEAABkiCAAQASsACfAH4AVwBGADUAIw
 @echo:nGIAAEABAAAZIggAE/IM8ArgCNAGwARwA2ACMCRjAAABAAAAHj8AAEE/AACWZAAA
 @echo:zD8AAHkAAAABBgIABlICUBkwCwAfNM4AHwHEABDwDuAM0ArACHAHYAZQAACcYgAA
 @echo:EAYAAAEPBgAPZAgADzQGAA8yC3ABFAoAFDQNABQyEPAO4AzQCsAIcAdgBlAZNQQA
 @echo:JAENBhAwD1CcYgAAUDAAAAEUCAAUZAgAFFQHABQ0BgAUMhBwAQQBAARiAAAJFQgA
 @echo:FXQKABVkCQAVNAgAFVIR8GhbAAABAAAAlVkAAPtaAAC8ZAAA+1oAAAEAAAABBAEA
 @echo:BOIAAAEMAgAMAREACQQBAAQiAABoWwAAAQAAANxeAAASXwAAAQAAABJfAAAJCgQA
 @echo:CjQGAAoyBnBoWwAAAQAAAO1fAAAgYAAAcGQAACBgAAABDQQADTQJAA0yBlAAAAAA
 @echo:AQAAAAEYAQAYwgAAAQIBAAIwAAAAAAAAAgQDAAEWAAYEEgAAAQAAAPB1AABwlgAA
 @echo:AEABANh+AAD4fgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAADofgAAAAAAAAAAAAAAAAAAAABDaGFyVG9PZW1BAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAADwggAAAAAAAAAAAADKhgAAYHMAAIiEAAAAAAAAAAAAAGaHAAD4dAAA
 @echo:aIEAAAAAAAAAAAAApooAANhxAAD4gAAAAAAAAAAAAADGigAAaHEAABCBAAAAAAAA
 @echo:AAAAAOqKAACAcQAAqIIAAAAAAAAAAAAADosAABhzAAA4ggAAAAAAAAAAAAAwiwAA
 @echo:qHIAAJiCAAAAAAAAAAAAAF6LAAAIcwAAIIIAAAAAAAAAAAAAiosAAJByAABIgQAA
 @echo:AAAAAAAAAACsiwAAuHEAAMCBAAAAAAAAAAAAANaLAAAwcgAA0IEAAAAAAAAAAAAA
 @echo:+IsAAEByAAAAggAAAAAAAAAAAAAYjAAAcHIAAOCBAAAAAAAAAAAAAECMAABQcgAA
 @echo:sIEAAAAAAAAAAAAAbIwAACByAABYggAAAAAAAAAAAACMjAAAyHIAAMiCAAAAAAAA
 @echo:AAAAALaMAAA4cwAA8IEAAAAAAAAAAAAA2IwAAGByAACIggAAAAAAAAAAAAACjQAA
 @echo:+HIAANiCAAAAAAAAAAAAACaNAABIcwAA6IAAAAAAAAAAAAAApI0AAFhxAAA4gQAA
 @echo:AAAAAAAAAADIjQAAqHEAACiBAAAAAAAAAAAAAO6NAACYcQAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAABYjQAAAAAAAAAAAAAAAAAAEogAAAAAAACqhwAAAAAAAAAAAAAAAAAA
 @echo:wocAAAAAAADghwAAAAAAAAAAAAAAAAAAjI0AAAAAAAAAAAAAAAAAAHSNAAAAAAAA
 @echo:AAAAAAAAAADciQAAAAAAAMCJAAAAAAAAxogAAAAAAAAAAAAAAAAAADiIAAAAAAAA
 @echo:gocAAAAAAABaiQAAAAAAANaIAAAAAAAAkocAAAAAAACehwAAAAAAAOyIAAAAAAAA
 @echo:cIcAAAAAAAAAAAAAAAAAAEaJAAAAAAAAAAAAAAAAAAD6iAAAAAAAAAAAAAAAAAAA
 @echo:CIkAAAAAAAAAAAAAAAAAADCJAAAAAAAAAAAAAAAAAAAiigAAAAAAAAAAAAAAAAAA
 @echo:HokAAAAAAAB2iQAAAAAAAIiJAAAAAAAAAAAAAAAAAACoiQAAAAAAAJyIAAAAAAAA
 @echo:AAAAAAAAAAAoiAAAAAAAAISIAAAAAAAArogAAAAAAAAAAAAAAAAAAPqJAAAAAAAA
 @echo:DooAAAAAAABoiQAAAAAAAFCKAAAAAAAAZooAAAAAAAAAAAAAAAAAADaKAAAAAAAA
 @echo:AAAAAAAAAAB4iAAAAAAAAAAAAAAAAAAAXIgAAAAAAABEiAAAAAAAAPqHAAAAAAAA
 @echo:AAAAAAAAAAC4iQAAAAAAAAAAAAAAAAAAlooAAAAAAAB8igAAAAAAAAAAAAAAAAAA
 @echo:6oQAAAAAAADAhAAAAAAAAOCEAAAAAAAA9oQAAAAAAAB8hQAAAAAAAIaFAAAAAAAA
 @echo:kIUAAAAAAAAChQAAAAAAAJqFAAAAAAAAooUAAAAAAABshQAAAAAAAGCFAAAAAAAA
 @echo:VIUAAAAAAACqhQAAAAAAABCFAAAAAAAAtIUAAAAAAAC+hQAAAAAAABSOAAAAAAAA
 @echo:SoUAAAAAAAAejgAAAAAAAEKFAAAAAAAAOIUAAAAAAADWhgAAAAAAAL6GAAAAAAAA
 @echo:tIYAAAAAAACohgAAAAAAAJSGAAAAAAAAioYAAAAAAACChgAAAAAAAHCGAAAAAAAA
 @echo:YIYAAAAAAADYhAAAAAAAAC6FAAAAAAAAUoYAAAAAAABEhgAAAAAAADiGAAAAAAAA
 @echo:LoYAAAAAAAAkhQAAAAAAACCGAAAAAAAAFIYAAAAAAAAGhgAAAAAAAPyFAAAAAAAA
 @echo:9IUAAAAAAADqhQAAAAAAAN6FAAAAAAAA1IUAAAAAAADKhQAAAAAAAEqNAAAAAAAA
 @echo:GoUAAAAAAAAojgAAAAAAAAAAAAAAAAAAJIcAAAAAAAAQhwAAAAAAAASHAAAAAAAA
 @echo:6oYAAAAAAAA4hwAAAAAAAFKHAAAAAAAAAAAAAAAAAABXAF9fQ19zcGVjaWZpY19o
 @echo:YW5kbGVyAAAyBGV4aXQAABYDX3N0cnVwcgDPBHN0cm5jcHlfcwACA19zdHJuY29s
 @echo:bAAGA19zdHJuaWNvbGwAAG0EaXN1cHBlcgDDBHN0cmNvbGwAxgRzdHJjc3BuAGQE
 @echo:aXNhbHBoYQD+Al9zdHJsd3IATARmcmVlAABpBGlzbG93ZXIAxQRzdHJjcHlfcwAA
 @echo:wARzdHJjYXRfcwAA6AJfc3BsaXRwYXRoX3MAAIYEbWFsbG9jAADYAV9pdG9hX3MA
 @echo:OANfdWx0b2EAACoEY2xvY2sAQwRmb3BlbgA2BGZjbG9zZQAA6QR0b2xvd2VyAMgC
 @echo:X3NldG1vZGUAAIMBX2lzYXR0eQBFBGZwcmludGYAewRpc3hkaWdpdAAAYwRpc2Fs
 @echo:bnVtADwEZmdldHMAGwFfZmlsZW5vANwEc3dwcmludGZfcwAA+gJfc3RyaWNtcAAA
 @echo:6gNfd3NldGxvY2FsZQDBBHN0cmNocgAAuQRzcHJpbnRmX3MAVQBfWGNwdEZpbHRl
 @echo:cgCuAF9hbXNnX2V4aXQAAH8AX19nZXRtYWluYXJncwCOAF9fc2V0X2FwcF90eXBl
 @echo:AAAOAV9leGl0AMEAX2NleGl0AACQAF9fc2V0dXNlcm1hdGhlcnIAAH0BX2luaXR0
 @echo:ZXJtACcBX2Ztb2RlAADSAF9jb21tb2RlAABtc3ZjcnQuZGxsAAAvAD90ZXJtaW5h
 @echo:dGVAQFlBWFhaAO8EUnRsTXVsdGlCeXRlVG9Vbmljb2RlTgAAIgBEYmdQcmludAAA
 @echo:/QVSdGxVbmljb2RlVG9PZW1OAADyAlJ0bENhcHR1cmVDb250ZXh0AOgEUnRsTG9v
 @echo:a3VwRnVuY3Rpb25FbnRyeQAAJwZSdGxWaXJ0dWFsVW53aW5kAABudGRsbC5kbGwA
 @echo:EABGaW5kRmlyc3RGaWxlQQAAGABGaW5kTmV4dEZpbGVBAAwARmluZENsb3NlAEkA
 @echo:UmVhZEZpbGUAABAAU2V0Q29uc29sZUN0cmxIYW5kbGVyAAkAR2V0Q29uc29sZVNj
 @echo:cmVlbkJ1ZmZlckluZm8AABwAU2V0Q29uc29sZVRleHRBdHRyaWJ1dGUAEQBFbnRl
 @echo:ckNyaXRpY2FsU2VjdGlvbgAABwBHZXRDb25zb2xlT3V0cHV0Q1AAAAwAR2V0U3Rk
 @echo:SGFuZGxlAABbAFdyaXRlRmlsZQAdAExlYXZlQ3JpdGljYWxTZWN0aW9uAAAYAElu
 @echo:aXRpYWxpemVDcml0aWNhbFNlY3Rpb24ACgBsc3RybGVuQQAABgBHZXRDdXJyZW50
 @echo:RGlyZWN0b3J5QQAAJABVbm1hcFZpZXdPZkZpbGUAEQBTZXRDdXJyZW50RGlyZWN0
 @echo:b3J5QQAABQBHZXRMYXN0RXJyb3IAACkAR2V0RmlsZUF0dHJpYnV0ZXNBAAAFAENy
 @echo:ZWF0ZUZpbGVBAAAAQ2xvc2VIYW5kbGUACgBIZWFwU2V0SW5mb3JtYXRpb24AACoA
 @echo:SXNEQkNTTGVhZEJ5dGUAAAgAQ3JlYXRlRmlsZU1hcHBpbmdBAABQAFNldEZpbGVB
 @echo:cGlzVG9PRU0AAC4AR2V0RmlsZVNpemUACABFeGl0UHJvY2VzcwAIAEZvcm1hdE1l
 @echo:c3NhZ2VBAAA9AFNldFRocmVhZFByZWZlcnJlZFVJTGFuZ3VhZ2VzABAATWFwVmll
 @echo:d09mRmlsZQAtAFNsZWVwABEAVW5oYW5kbGVkRXhjZXB0aW9uRmlsdGVyAAAPAFNl
 @echo:dFVuaGFuZGxlZEV4Y2VwdGlvbkZpbHRlcgAMAEdldEN1cnJlbnRQcm9jZXNzAE4A
 @echo:VGVybWluYXRlUHJvY2VzcwAAFABHZXRNb2R1bGVIYW5kbGVXAAAAAFF1ZXJ5UGVy
 @echo:Zm9ybWFuY2VDb3VudGVyAA0AR2V0Q3VycmVudFByb2Nlc3NJZAARAEdldEN1cnJl
 @echo:bnRUaHJlYWRJZAAAFgBHZXRTeXN0ZW1UaW1lQXNGaWxlVGltZQAaAEdldFRpY2tD
 @echo:b3VudAAAYXBpLW1zLXdpbi1jb3JlLWZpbGUtbDEtMS0wLmRsbABhcGktbXMtd2lu
 @echo:LWNvcmUtY29uc29sZS1sMS0xLTAuZGxsAABhcGktbXMtd2luLWNvcmUtY29uc29s
 @echo:ZS1sMi0xLTAuZGxsAABhcGktbXMtd2luLWNvcmUtc3luY2gtbDEtMS0wLmRsbAAA
 @echo:YXBpLW1zLXdpbi1jb3JlLXByb2Nlc3NlbnZpcm9ubWVudC1sMS0xLTAuZGxsAGFw
 @echo:aS1tcy13aW4tY29yZS1zdHJpbmctb2Jzb2xldGUtbDEtMS0wLmRsbAAAYXBpLW1z
 @echo:LXdpbi1jb3JlLW1lbW9yeS1sMS0xLTAuZGxsAGFwaS1tcy13aW4tY29yZS1lcnJv
 @echo:cmhhbmRsaW5nLWwxLTEtMC5kbGwAAGFwaS1tcy13aW4tY29yZS1oYW5kbGUtbDEt
 @echo:MS0wLmRsbABhcGktbXMtd2luLWNvcmUtaGVhcC1sMS0xLTAuZGxsAGFwaS1tcy13
 @echo:aW4tY29yZS1sb2NhbGl6YXRpb24tbDEtMi0wLmRsbABhcGktbXMtd2luLWNvcmUt
 @echo:a2VybmVsMzItbGVnYWN5LWwxLTEtMC5kbGwAAGFwaS1tcy13aW4tY29yZS1maWxl
 @echo:LWwxLTItMi5kbGwAYXBpLW1zLXdpbi1jb3JlLXByb2Nlc3N0aHJlYWRzLWwxLTEt
 @echo:MC5kbGwAYXBpLW1zLXdpbi1jb3JlLXN5bmNoLWwxLTItMC5kbGwAAGFwaS1tcy13
 @echo:aW4tY29yZS1saWJyYXJ5bG9hZGVyLWwxLTItMC5kbGwAAGFwaS1tcy13aW4tY29y
 @echo:ZS1wcm9maWxlLWwxLTEtMC5kbGwAAGFwaS1tcy13aW4tY29yZS1zeXNpbmZvLWwx
 @echo:LTEtMC5kbGwAAIEAX19pb2JfZnVuYwAAAABBcGlTZXRRdWVyeUFwaVNldFByZXNl
 @echo:bmNlAAEAUmVzb2x2ZURlbGF5TG9hZGVkQVBJAAAARGVsYXlMb2FkRmFpbHVyZUhv
 @echo:b2sAAGFwaS1tcy13aW4tY29yZS1hcGlxdWVyeS1sMS0xLTAuZGxsAGFwaS1tcy13
 @echo:aW4tY29yZS1kZWxheWxvYWQtbDEtMS0xLmRsbAAAYXBpLW1zLXdpbi1jb3JlLWRl
 @echo:bGF5bG9hZC1sMS0xLTAuZGxsAACSBG1lbWNweQAAlARtZW1tb3ZlAJYEbWVtc2V0
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACANQBAAQAAACAzAEABAAAA
 @echo:wDQAQAEAAADg5ABAAQAAAOAEAUABAAAApKQAQAEAAACoxABAAQAAAAAAAAAAAAAA
 @echo:AIAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAMqLfLZkrAADNXSDSZtT//wAAAAAAAAAA
 @echo:XgAAACQAAABbXkEtWmEtejAtOV9dAAAAAQAAAAEAAAD//////////wEAAAAAAAAA
 @echo:ACAAAAAgAAD/////AQAAAAEAAAD/////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAgQAAABEQAAyHoAAAgRAAAZEgAA2HoAACASAAC4EgAA
 @echo:6HoAAMASAABFFwAA8HoAAEwXAACTGAAAGHsAALQYAABaGgAAMHsAAGAaAABGHQAA
 @echo:UHsAAFAdAAByHgAAdHsAAHgeAACCHwAAqHsAAIgfAAAKJgAAxHsAABAmAABFJgAA
 @echo:6HsAAEwmAACAJgAA8HsAAIgmAADUJgAA+HsAANwmAACXJwAAAHwAAKAnAAAjKAAA
 @echo:yHoAACwoAAA6KQAAGHwAAEApAAAeLAAAMHwAADAsAAD4LAAASHwAAAAtAAChLwAA
 @echo:YHwAAKgvAAAfMAAAgHwAACgwAADQMAAAlHwAAOAwAABPMQAA8HsAAGAxAAAUMwAA
 @echo:oHwAACAzAACcNAAAwHwAAMA0AAByNQAA3HwAAIA1AAANOAAA6HwAABQ4AAD4OQAA
 @echo:DH0AAAA6AAA2OwAAAHwAADw7AAA9QAAAKH0AAERAAAA8UQAAYH0AAERRAADJUQAA
 @echo:hH0AANBRAACOUgAAGHwAAABTAAAnVAAAqHsAADBUAADRVQAAlH0AABBWAACKVwAA
 @echo:rH0AAJBXAAD4VwAAwH0AAABYAAA9WAAA1H0AAFBYAAAjWQAA8HsAADBZAAB5WQAA
 @echo:1H0AAIBZAAA+WwAA3H0AAFBbAABiWwAA8HsAAIBbAACeWwAACH4AAKRbAADYWwAA
 @echo:6HsAAOBbAABRXQAAFH4AAFhdAABPXgAADH4AAGBeAACZXgAA8HsAAKBeAAC4XgAA
 @echo:8HsAAMxeAAAgXwAAHH4AAChfAABtXwAA6HsAAOBfAAAtYAAAPH4AAHRgAABIYQAA
 @echo:YH4AAHhhAACWYQAA6HsAAKhhAAAfYgAAdH4AAChiAAB2YgAA8HsAAJxiAAC5YgAA
 @echo:8HsAAMBiAAAbYwAAfH4AACRjAACqYwAAAHwAAPBjAADyYwAAcH4AABBkAABdZAAA
 @echo:iH4AAHBkAACQZAAAoHsAAJZkAAC2ZAAAWH0AALxkAADaZAAAoHsAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACcYQBAAQAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAgDoAACAKAAAgBAAAABAAACA
 @echo:GAAAAFgAAIAAAAAAAAAAAAAAAAAAAAEAAQAAAHAAAIAAAAAAAAAAAAAAAAAAAAEA
 @echo:AQAAAIgAAIAAAAAAAAAAAAAAAAAAAAEAAQAAAKAAAIAAAAAAAAAAAAAAAAAAAAEA
 @echo:CQQAALgAAAAAAAAAAAAAAAAAAAAAAAEACQQAAMgAAAAAAAAAAAAAAAAAAAAAAAEA
 @echo:CQQAANgAAABAVwEAyAAAAAAAAAAAAAAAoFMBAJwDAAAAAAAAAAAAAPBQAQCuAgAA
 @echo:AAAAAAAAAAADAE0AVQBJADw/eG1sIHZlcnNpb249IjEuMCIgZW5jb2Rpbmc9IlVU
 @echo:Ri04IiBzdGFuZGFsb25lPSJ5ZXMiPz4NCjwhLS0gQ29weXJpZ2h0IChjKSBNaWNy
 @echo:b3NvZnQgQ29ycG9yYXRpb24gLS0+DQo8YXNzZW1ibHkgeG1sbnM9InVybjpzY2hl
 @echo:bWFzLW1pY3Jvc29mdC1jb206YXNtLnYxIiBtYW5pZmVzdFZlcnNpb249IjEuMCI+
 @echo:DQo8YXNzZW1ibHlJZGVudGl0eQ0KICAgIHZlcnNpb249IjUuMS4wLjAiDQogICAg
 @echo:cHJvY2Vzc29yQXJjaGl0ZWN0dXJlPSJhbWQ2NCINCiAgICBuYW1lPSJNaWNyb3Nv
 @echo:ZnQuV2luZG93cy5GaWxlc3lzdGVtLkZpbmRzdHIiDQogICAgdHlwZT0id2luMzIi
 @echo:DQovPg0KPGRlc2NyaXB0aW9uPkZpbmQgU3RyaW5nIChRR1JFUCkgVXRpbGl0eTwv
 @echo:ZGVzY3JpcHRpb24+DQoNCjx0cnVzdEluZm8geG1sbnM9InVybjpzY2hlbWFzLW1p
 @echo:Y3Jvc29mdC1jb206YXNtLnYzIj4NCiAgICA8c2VjdXJpdHk+DQogICAgICAgIDxy
 @echo:ZXF1ZXN0ZWRQcml2aWxlZ2VzPg0KICAgICAgICAgICAgPHJlcXVlc3RlZEV4ZWN1
 @echo:dGlvbkxldmVsDQogICAgICAgICAgICAgICAgbGV2ZWw9ImFzSW52b2tlciINCiAg
 @echo:ICAgICAgICAgICAgICB1aUFjY2Vzcz0iZmFsc2UiDQogICAgICAgICAgICAvPg0K
 @echo:ICAgICAgICA8L3JlcXVlc3RlZFByaXZpbGVnZXM+DQogICAgPC9zZWN1cml0eT4N
 @echo:CjwvdHJ1c3RJbmZvPg0KPC9hc3NlbWJseT4NCg0KAACMAzQAAABWAFMAXwBWAEUA
 @echo:UgBTAEkATwBOAF8ASQBOAEYATwAAAAAAvQTv/gAAAQAAAAoAAQBhSgAACgABAGFK
 @echo:PwAAAAAAAAAEAAQAAQAAAAAAAAAAAAAAAAAAAOoCAAABAFMAdAByAGkAbgBnAEYA
 @echo:aQBsAGUASQBuAGYAbwAAAMYCAAABADAANAAwADkAMAA0AEIAMAAAAEwAFgABAEMA
 @echo:bwBtAHAAYQBuAHkATgBhAG0AZQAAAAAATQBpAGMAcgBvAHMAbwBmAHQAIABDAG8A
 @echo:cgBwAG8AcgBhAHQAaQBvAG4AAABgABwAAQBGAGkAbABlAEQAZQBzAGMAcgBpAHAA
 @echo:dABpAG8AbgAAAAAARgBpAG4AZAAgAFMAdAByAGkAbgBnACAAKABRAEcAUgBFAFAA
 @echo:KQAgAFUAdABpAGwAaQB0AHkAAABoACQAAQBGAGkAbABlAFYAZQByAHMAaQBvAG4A
 @echo:AAAAADEAMAAuADAALgAxADkAMAA0ADEALgAxACAAKABXAGkAbgBCAHUAaQBsAGQA
 @echo:LgAxADYAMAAxADAAMQAuADAAOAAwADAAKQAAADAACAABAEkAbgB0AGUAcgBuAGEA
 @echo:bABOAGEAbQBlAAAAZgBpAG4AZABzAHQAcgAAAIAALgABAEwAZQBnAGEAbABDAG8A
 @echo:cAB5AHIAaQBnAGgAdAAAAKkAIABNAGkAYwByAG8AcwBvAGYAdAAgAEMAbwByAHAA
 @echo:bwByAGEAdABpAG8AbgAuACAAQQBsAGwAIAByAGkAZwBoAHQAcwAgAHIAZQBzAGUA
 @echo:cgB2AGUAZAAuAAAAQAAMAAEATwByAGkAZwBpAG4AYQBsAEYAaQBsAGUAbgBhAG0A
 @echo:ZQAAAEYASQBOAEQAUwBUAFIALgBFAFgARQAAAGoAJQABAFAAcgBvAGQAdQBjAHQA
 @echo:TgBhAG0AZQAAAAAATQBpAGMAcgBvAHMAbwBmAHQArgAgAFcAaQBuAGQAbwB3AHMA
 @echo:rgAgAE8AcABlAHIAYQB0AGkAbgBnACAAUwB5AHMAdABlAG0AAAAAAD4ADQABAFAA
 @echo:cgBvAGQAdQBjAHQAVgBlAHIAcwBpAG8AbgAAADEAMAAuADAALgAxADkAMAA0ADEA
 @echo:LgAxAAAAAABEAAAAAQBWAGEAcgBGAGkAbABlAEkAbgBmAG8AAAAAACQABAAAAFQA
 @echo:cgBhAG4AcwBsAGEAdABpAG8AbgAAAAAACQSwBAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:zf7N/sgAAAAAAAEAAAAAABEAAAAAAAAAAgAAABtgDJMt+EvbFkYjRLlDQ3AuVc+d
 @echo:g5Ow79sMU+Br0fhVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiAAAAA4AAACYAAAA
 @echo:CAAAAKAAAAAOAAAAsAAAAAgAAAAAAAAAAAAAALgAAAAMAAAAAAAAAE0AVQBJAAAA
 @echo:AAAAAAAAAAAQAAAAGAAAAE0AVQBJAAAAAAAAAAAAAAALAAAAEAAAAGUAbgAtAFUA
 @echo:UwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAALAAAAACgCKAYoCCg
 @echo:KKAwoDigmKCwoLigwKDgoDClOKVIpWClaKUAAACQAAAYAAAAAKAIoBCgGKAgoCig
 @echo:MKAAAABAAQAMAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 @echo:AAAAAAAAAAAAAAAAAAAAAA==
 @echo:-----END CERTIFICATE-----
 @goto:EOF
